/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcBuildingElementType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcbuildingelementtype extends AEntity {
	public EIfcbuildingelementtype getByIndex(int index) throws SdaiException {
		return (EIfcbuildingelementtype)getByIndexEntity(index);
	}
	public EIfcbuildingelementtype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcbuildingelementtype)getCurrentMemberObject(iter);
	}
}
