/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcProduct of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcproduct extends AEntity {
	public EIfcproduct getByIndex(int index) throws SdaiException {
		return (EIfcproduct)getByIndexEntity(index);
	}
	public EIfcproduct getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcproduct)getCurrentMemberObject(iter);
	}
}
