/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcPipeSegmentType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcpipesegmenttype extends AEntity {
	public EIfcpipesegmenttype getByIndex(int index) throws SdaiException {
		return (EIfcpipesegmenttype)getByIndexEntity(index);
	}
	public EIfcpipesegmenttype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcpipesegmenttype)getCurrentMemberObject(iter);
	}
}
