/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcCartesianPointList3D of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfccartesianpointlist3d extends AEntity {
	public EIfccartesianpointlist3d getByIndex(int index) throws SdaiException {
		return (EIfccartesianpointlist3d)getByIndexEntity(index);
	}
	public EIfccartesianpointlist3d getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfccartesianpointlist3d)getCurrentMemberObject(iter);
	}
}
