/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcRelConnectsWithRealizingElements of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcrelconnectswithrealizingelements extends AEntity {
	public EIfcrelconnectswithrealizingelements getByIndex(int index) throws SdaiException {
		return (EIfcrelconnectswithrealizingelements)getByIndexEntity(index);
	}
	public EIfcrelconnectswithrealizingelements getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcrelconnectswithrealizingelements)getCurrentMemberObject(iter);
	}
}
