/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcCoordinateOperation of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfccoordinateoperation extends AEntity {
	public EIfccoordinateoperation getByIndex(int index) throws SdaiException {
		return (EIfccoordinateoperation)getByIndexEntity(index);
	}
	public EIfccoordinateoperation getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfccoordinateoperation)getCurrentMemberObject(iter);
	}
}
