/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcGeometricCurveSet of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcgeometriccurveset extends AEntity {
	public EIfcgeometriccurveset getByIndex(int index) throws SdaiException {
		return (EIfcgeometriccurveset)getByIndexEntity(index);
	}
	public EIfcgeometriccurveset getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcgeometriccurveset)getCurrentMemberObject(iter);
	}
}
