/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcTopologicalRepresentationItem of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfctopologicalrepresentationitem extends AEntity {
	public EIfctopologicalrepresentationitem getByIndex(int index) throws SdaiException {
		return (EIfctopologicalrepresentationitem)getByIndexEntity(index);
	}
	public EIfctopologicalrepresentationitem getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfctopologicalrepresentationitem)getCurrentMemberObject(iter);
	}
}
