/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcFeatureElement of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcfeatureelement extends AEntity {
	public EIfcfeatureelement getByIndex(int index) throws SdaiException {
		return (EIfcfeatureelement)getByIndexEntity(index);
	}
	public EIfcfeatureelement getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcfeatureelement)getCurrentMemberObject(iter);
	}
}
