/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcRelConnectsPorts of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcrelconnectsports extends AEntity {
	public EIfcrelconnectsports getByIndex(int index) throws SdaiException {
		return (EIfcrelconnectsports)getByIndexEntity(index);
	}
	public EIfcrelconnectsports getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcrelconnectsports)getCurrentMemberObject(iter);
	}
}
