/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcElementQuantity of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcelementquantity extends AEntity {
	public EIfcelementquantity getByIndex(int index) throws SdaiException {
		return (EIfcelementquantity)getByIndexEntity(index);
	}
	public EIfcelementquantity getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcelementquantity)getCurrentMemberObject(iter);
	}
}
