/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcUnitaryControlElement of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcunitarycontrolelement extends AEntity {
	public EIfcunitarycontrolelement getByIndex(int index) throws SdaiException {
		return (EIfcunitarycontrolelement)getByIndexEntity(index);
	}
	public EIfcunitarycontrolelement getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcunitarycontrolelement)getCurrentMemberObject(iter);
	}
}
