/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcEnergyConversionDevice of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcenergyconversiondevice extends AEntity {
	public EIfcenergyconversiondevice getByIndex(int index) throws SdaiException {
		return (EIfcenergyconversiondevice)getByIndexEntity(index);
	}
	public EIfcenergyconversiondevice getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcenergyconversiondevice)getCurrentMemberObject(iter);
	}
}
