/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcConnectionPointGeometry of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcconnectionpointgeometry extends AEntity {
	public EIfcconnectionpointgeometry getByIndex(int index) throws SdaiException {
		return (EIfcconnectionpointgeometry)getByIndexEntity(index);
	}
	public EIfcconnectionpointgeometry getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcconnectionpointgeometry)getCurrentMemberObject(iter);
	}
}
