/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcCurveStyleFont of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfccurvestylefont extends AEntity {
	public EIfccurvestylefont getByIndex(int index) throws SdaiException {
		return (EIfccurvestylefont)getByIndexEntity(index);
	}
	public EIfccurvestylefont getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfccurvestylefont)getCurrentMemberObject(iter);
	}
}
