/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcCoilType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfccoiltype extends AEntity {
	public EIfccoiltype getByIndex(int index) throws SdaiException {
		return (EIfccoiltype)getByIndexEntity(index);
	}
	public EIfccoiltype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfccoiltype)getCurrentMemberObject(iter);
	}
}
