/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcMaterialDefinition of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcmaterialdefinition extends AEntity {
	public EIfcmaterialdefinition getByIndex(int index) throws SdaiException {
		return (EIfcmaterialdefinition)getByIndexEntity(index);
	}
	public EIfcmaterialdefinition getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcmaterialdefinition)getCurrentMemberObject(iter);
	}
}
