/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcDuctSegment of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcductsegment extends AEntity {
	public EIfcductsegment getByIndex(int index) throws SdaiException {
		return (EIfcductsegment)getByIndexEntity(index);
	}
	public EIfcductsegment getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcductsegment)getCurrentMemberObject(iter);
	}
}
