/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcPropertySingleValue of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcpropertysinglevalue extends AEntity {
	public EIfcpropertysinglevalue getByIndex(int index) throws SdaiException {
		return (EIfcpropertysinglevalue)getByIndexEntity(index);
	}
	public EIfcpropertysinglevalue getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcpropertysinglevalue)getCurrentMemberObject(iter);
	}
}
