/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcPlacement of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcplacement extends AEntity {
	public EIfcplacement getByIndex(int index) throws SdaiException {
		return (EIfcplacement)getByIndexEntity(index);
	}
	public EIfcplacement getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcplacement)getCurrentMemberObject(iter);
	}
}
