/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcProxy of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcproxy extends AEntity {
	public EIfcproxy getByIndex(int index) throws SdaiException {
		return (EIfcproxy)getByIndexEntity(index);
	}
	public EIfcproxy getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcproxy)getCurrentMemberObject(iter);
	}
}
