/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcStructuralLoadSingleForceWarping of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcstructuralloadsingleforcewarping extends AEntity {
	public EIfcstructuralloadsingleforcewarping getByIndex(int index) throws SdaiException {
		return (EIfcstructuralloadsingleforcewarping)getByIndexEntity(index);
	}
	public EIfcstructuralloadsingleforcewarping getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcstructuralloadsingleforcewarping)getCurrentMemberObject(iter);
	}
}
