/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcProjectOrder of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcprojectorder extends AEntity {
	public EIfcprojectorder getByIndex(int index) throws SdaiException {
		return (EIfcprojectorder)getByIndexEntity(index);
	}
	public EIfcprojectorder getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcprojectorder)getCurrentMemberObject(iter);
	}
}
