/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcMaterialClassificationRelationship of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcmaterialclassificationrelationship extends AEntity {
	public EIfcmaterialclassificationrelationship getByIndex(int index) throws SdaiException {
		return (EIfcmaterialclassificationrelationship)getByIndexEntity(index);
	}
	public EIfcmaterialclassificationrelationship getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcmaterialclassificationrelationship)getCurrentMemberObject(iter);
	}
}
