/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcCurtainWall of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfccurtainwall extends AEntity {
	public EIfccurtainwall getByIndex(int index) throws SdaiException {
		return (EIfccurtainwall)getByIndexEntity(index);
	}
	public EIfccurtainwall getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfccurtainwall)getCurrentMemberObject(iter);
	}
}
