/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcHumidifier of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfchumidifier extends AEntity {
	public EIfchumidifier getByIndex(int index) throws SdaiException {
		return (EIfchumidifier)getByIndexEntity(index);
	}
	public EIfchumidifier getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfchumidifier)getCurrentMemberObject(iter);
	}
}
