/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcTank of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfctank extends AEntity {
	public EIfctank getByIndex(int index) throws SdaiException {
		return (EIfctank)getByIndexEntity(index);
	}
	public EIfctank getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfctank)getCurrentMemberObject(iter);
	}
}
