/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcPreDefinedItem of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcpredefineditem extends AEntity {
	public EIfcpredefineditem getByIndex(int index) throws SdaiException {
		return (EIfcpredefineditem)getByIndexEntity(index);
	}
	public EIfcpredefineditem getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcpredefineditem)getCurrentMemberObject(iter);
	}
}
