/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcPresentationStyleSelect of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcpresentationstyleselect extends CAggregate {
	public static final int sIfcnullstyle = 2;

	public int testByIndex(int index) throws SdaiException {
		return pTestByIndex(index);
	}

	public int testCurrentMember(SdaiIterator iter) throws SdaiException {
		return pTestCurrentMember(iter);
	}

	public boolean isMember(int value, EIfcnullstyle node1) throws SdaiException { // case 2
		return pIsMember(value, 2);
	}
	public int getByIndex(int index, EIfcnullstyle node1) throws SdaiException { // case 2
		return pGetByIndexInt(index, 2);
	}
	public int getCurrentMember(SdaiIterator iter, EIfcnullstyle node1) throws SdaiException { // case 2
		return pGetCurrentMemberInt(iter, 2);
	}
	public void setByIndex(int index, int value, EIfcnullstyle node1) throws SdaiException { // case 2
		pSetByIndex(index, value, 2);
	}
	public void setCurrentMember(SdaiIterator iter, int value, EIfcnullstyle node1) throws SdaiException { // case 2
		pSetCurrentMember(iter, value, 2);
	}
	public void addBefore(SdaiIterator iter, int value, EIfcnullstyle node1) throws SdaiException { // case 2
		pAddBefore(iter, value, 2);
	}
	public void addAfter(SdaiIterator iter, int value, EIfcnullstyle node1) throws SdaiException { // case 2
		pAddAfter(iter, value, 2);
	}
	public void addUnordered(int value, EIfcnullstyle node1) throws SdaiException { // case 2
		pAddUnordered(value, 2);
	}
	public void addByIndex(int index, int value, EIfcnullstyle node1) throws SdaiException { // case 2
		pAddByIndex(index, value, 2);
	}
	public void removeUnordered(int value, EIfcnullstyle node1) throws SdaiException { // case 2
		pRemoveUnordered(value, 2);
	}
}
