/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcMaterialLayerWithOffsets of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcmateriallayerwithoffsets extends AEntity {
	public EIfcmateriallayerwithoffsets getByIndex(int index) throws SdaiException {
		return (EIfcmateriallayerwithoffsets)getByIndexEntity(index);
	}
	public EIfcmateriallayerwithoffsets getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcmateriallayerwithoffsets)getCurrentMemberObject(iter);
	}
}
