/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcTendonType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfctendontype extends AEntity {
	public EIfctendontype getByIndex(int index) throws SdaiException {
		return (EIfctendontype)getByIndexEntity(index);
	}
	public EIfctendontype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfctendontype)getCurrentMemberObject(iter);
	}
}
