/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcRelSpaceBoundary1stLevel of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcrelspaceboundary1stlevel extends AEntity {
	public EIfcrelspaceboundary1stlevel getByIndex(int index) throws SdaiException {
		return (EIfcrelspaceboundary1stlevel)getByIndexEntity(index);
	}
	public EIfcrelspaceboundary1stlevel getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcrelspaceboundary1stlevel)getCurrentMemberObject(iter);
	}
}
