/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcRationalBSplineSurfaceWithKnots of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcrationalbsplinesurfacewithknots extends AEntity {
	public EIfcrationalbsplinesurfacewithknots getByIndex(int index) throws SdaiException {
		return (EIfcrationalbsplinesurfacewithknots)getByIndexEntity(index);
	}
	public EIfcrationalbsplinesurfacewithknots getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcrationalbsplinesurfacewithknots)getCurrentMemberObject(iter);
	}
}
