/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcSubContractResourceType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcsubcontractresourcetype extends AEntity {
	public EIfcsubcontractresourcetype getByIndex(int index) throws SdaiException {
		return (EIfcsubcontractresourcetype)getByIndexEntity(index);
	}
	public EIfcsubcontractresourcetype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcsubcontractresourcetype)getCurrentMemberObject(iter);
	}
}
