/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcExtrudedAreaSolid of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcextrudedareasolid extends AEntity {
	public EIfcextrudedareasolid getByIndex(int index) throws SdaiException {
		return (EIfcextrudedareasolid)getByIndexEntity(index);
	}
	public EIfcextrudedareasolid getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcextrudedareasolid)getCurrentMemberObject(iter);
	}
}
