/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcStructuralLoad of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcstructuralload extends AEntity {
	public EIfcstructuralload getByIndex(int index) throws SdaiException {
		return (EIfcstructuralload)getByIndexEntity(index);
	}
	public EIfcstructuralload getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcstructuralload)getCurrentMemberObject(iter);
	}
}
