/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcLampType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfclamptype extends AEntity {
	public EIfclamptype getByIndex(int index) throws SdaiException {
		return (EIfclamptype)getByIndexEntity(index);
	}
	public EIfclamptype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfclamptype)getCurrentMemberObject(iter);
	}
}
