/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcAxis2Placement3D of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcaxis2placement3d extends AEntity {
	public EIfcaxis2placement3d getByIndex(int index) throws SdaiException {
		return (EIfcaxis2placement3d)getByIndexEntity(index);
	}
	public EIfcaxis2placement3d getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcaxis2placement3d)getCurrentMemberObject(iter);
	}
}
