/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcDistributionControlElementType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcdistributioncontrolelementtype extends AEntity {
	public EIfcdistributioncontrolelementtype getByIndex(int index) throws SdaiException {
		return (EIfcdistributioncontrolelementtype)getByIndexEntity(index);
	}
	public EIfcdistributioncontrolelementtype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcdistributioncontrolelementtype)getCurrentMemberObject(iter);
	}
}
