/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcMaterialUsageDefinition of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcmaterialusagedefinition extends AEntity {
	public EIfcmaterialusagedefinition getByIndex(int index) throws SdaiException {
		return (EIfcmaterialusagedefinition)getByIndexEntity(index);
	}
	public EIfcmaterialusagedefinition getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcmaterialusagedefinition)getCurrentMemberObject(iter);
	}
}
