/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcBSplineSurfaceWithKnots of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcbsplinesurfacewithknots extends AEntity {
	public EIfcbsplinesurfacewithknots getByIndex(int index) throws SdaiException {
		return (EIfcbsplinesurfacewithknots)getByIndexEntity(index);
	}
	public EIfcbsplinesurfacewithknots getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcbsplinesurfacewithknots)getCurrentMemberObject(iter);
	}
}
