/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcCondenser of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfccondenser extends AEntity {
	public EIfccondenser getByIndex(int index) throws SdaiException {
		return (EIfccondenser)getByIndexEntity(index);
	}
	public EIfccondenser getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfccondenser)getCurrentMemberObject(iter);
	}
}
