/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcTextStyleFontModel of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfctextstylefontmodel extends AEntity {
	public EIfctextstylefontmodel getByIndex(int index) throws SdaiException {
		return (EIfctextstylefontmodel)getByIndexEntity(index);
	}
	public EIfctextstylefontmodel getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfctextstylefontmodel)getCurrentMemberObject(iter);
	}
}
