/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcFillAreaStyleTiles of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcfillareastyletiles extends AEntity {
	public EIfcfillareastyletiles getByIndex(int index) throws SdaiException {
		return (EIfcfillareastyletiles)getByIndexEntity(index);
	}
	public EIfcfillareastyletiles getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcfillareastyletiles)getCurrentMemberObject(iter);
	}
}
