/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcCurveBoundedSurface of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfccurveboundedsurface extends AEntity {
	public EIfccurveboundedsurface getByIndex(int index) throws SdaiException {
		return (EIfccurveboundedsurface)getByIndexEntity(index);
	}
	public EIfccurveboundedsurface getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfccurveboundedsurface)getCurrentMemberObject(iter);
	}
}
