/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcRelAggregates of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcrelaggregates extends AEntity {
	public EIfcrelaggregates getByIndex(int index) throws SdaiException {
		return (EIfcrelaggregates)getByIndexEntity(index);
	}
	public EIfcrelaggregates getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcrelaggregates)getCurrentMemberObject(iter);
	}
}
