/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcMaterial of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcmaterial extends AEntity {
	public EIfcmaterial getByIndex(int index) throws SdaiException {
		return (EIfcmaterial)getByIndexEntity(index);
	}
	public EIfcmaterial getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcmaterial)getCurrentMemberObject(iter);
	}
}
