/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcArbitraryProfileDefWithVoids of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcarbitraryprofiledefwithvoids extends AEntity {
	public EIfcarbitraryprofiledefwithvoids getByIndex(int index) throws SdaiException {
		return (EIfcarbitraryprofiledefwithvoids)getByIndexEntity(index);
	}
	public EIfcarbitraryprofiledefwithvoids getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcarbitraryprofiledefwithvoids)getCurrentMemberObject(iter);
	}
}
