/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcMemberType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcmembertype extends AEntity {
	public EIfcmembertype getByIndex(int index) throws SdaiException {
		return (EIfcmembertype)getByIndexEntity(index);
	}
	public EIfcmembertype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcmembertype)getCurrentMemberObject(iter);
	}
}
