/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcComplexProperty of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfccomplexproperty extends AEntity {
	public EIfccomplexproperty getByIndex(int index) throws SdaiException {
		return (EIfccomplexproperty)getByIndexEntity(index);
	}
	public EIfccomplexproperty getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfccomplexproperty)getCurrentMemberObject(iter);
	}
}
