/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcRailingType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcrailingtype extends AEntity {
	public EIfcrailingtype getByIndex(int index) throws SdaiException {
		return (EIfcrailingtype)getByIndexEntity(index);
	}
	public EIfcrailingtype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcrailingtype)getCurrentMemberObject(iter);
	}
}
