/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcConstructionMaterialResource of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcconstructionmaterialresource extends AEntity {
	public EIfcconstructionmaterialresource getByIndex(int index) throws SdaiException {
		return (EIfcconstructionmaterialresource)getByIndexEntity(index);
	}
	public EIfcconstructionmaterialresource getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcconstructionmaterialresource)getCurrentMemberObject(iter);
	}
}
