/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcOrientedEdge of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcorientededge extends AEntity {
	public EIfcorientededge getByIndex(int index) throws SdaiException {
		return (EIfcorientededge)getByIndexEntity(index);
	}
	public EIfcorientededge getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcorientededge)getCurrentMemberObject(iter);
	}
}
