/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcRelDefinesByTemplate of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcreldefinesbytemplate extends AEntity {
	public EIfcreldefinesbytemplate getByIndex(int index) throws SdaiException {
		return (EIfcreldefinesbytemplate)getByIndexEntity(index);
	}
	public EIfcreldefinesbytemplate getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcreldefinesbytemplate)getCurrentMemberObject(iter);
	}
}
