/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcInterceptorType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcinterceptortype extends AEntity {
	public EIfcinterceptortype getByIndex(int index) throws SdaiException {
		return (EIfcinterceptortype)getByIndexEntity(index);
	}
	public EIfcinterceptortype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcinterceptortype)getCurrentMemberObject(iter);
	}
}
