/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcBSplineSurface of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcbsplinesurface extends AEntity {
	public EIfcbsplinesurface getByIndex(int index) throws SdaiException {
		return (EIfcbsplinesurface)getByIndexEntity(index);
	}
	public EIfcbsplinesurface getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcbsplinesurface)getCurrentMemberObject(iter);
	}
}
