/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcSpatialStructureElement of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcspatialstructureelement extends AEntity {
	public EIfcspatialstructureelement getByIndex(int index) throws SdaiException {
		return (EIfcspatialstructureelement)getByIndexEntity(index);
	}
	public EIfcspatialstructureelement getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcspatialstructureelement)getCurrentMemberObject(iter);
	}
}
