/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcTaskType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfctasktype extends AEntity {
	public EIfctasktype getByIndex(int index) throws SdaiException {
		return (EIfctasktype)getByIndexEntity(index);
	}
	public EIfctasktype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfctasktype)getCurrentMemberObject(iter);
	}
}
