/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcRelAssigns of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcrelassigns extends AEntity {
	public EIfcrelassigns getByIndex(int index) throws SdaiException {
		return (EIfcrelassigns)getByIndexEntity(index);
	}
	public EIfcrelassigns getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcrelassigns)getCurrentMemberObject(iter);
	}
}
