/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcRelCoversBldgElements of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcrelcoversbldgelements extends AEntity {
	public EIfcrelcoversbldgelements getByIndex(int index) throws SdaiException {
		return (EIfcrelcoversbldgelements)getByIndexEntity(index);
	}
	public EIfcrelcoversbldgelements getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcrelcoversbldgelements)getCurrentMemberObject(iter);
	}
}
