/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcCableSegmentType of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfccablesegmenttype extends AEntity {
	public EIfccablesegmenttype getByIndex(int index) throws SdaiException {
		return (EIfccablesegmenttype)getByIndexEntity(index);
	}
	public EIfccablesegmenttype getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfccablesegmenttype)getCurrentMemberObject(iter);
	}
}
