/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcDistributionElement of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcdistributionelement extends AEntity {
	public EIfcdistributionelement getByIndex(int index) throws SdaiException {
		return (EIfcdistributionelement)getByIndexEntity(index);
	}
	public EIfcdistributionelement getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcdistributionelement)getCurrentMemberObject(iter);
	}
}
