/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing aggregate of  IfcAxis1Placement of level 1

package jsdai.SIfc4;
import jsdai.lang.*;


public class AIfcaxis1placement extends AEntity {
	public EIfcaxis1placement getByIndex(int index) throws SdaiException {
		return (EIfcaxis1placement)getByIndexEntity(index);
	}
	public EIfcaxis1placement getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (EIfcaxis1placement)getCurrentMemberObject(iter);
	}
}
