/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing entity IfcRelAssignsToProduct

package jsdai.SIfc4;
import jsdai.lang.*;

public class CIfcrelassignstoproduct extends CIfcrelassigns implements EIfcrelassignstoproduct {
	public static final jsdai.dictionary.CEntity_definition definition = initEntityDefinition(CIfcrelassignstoproduct.class, SIfc4.ss);

	/*----------------------------- Attributes -----------*/

/*
	// GlobalId: protected String a0;   GlobalId - java inheritance - STRING
	// OwnerHistory: protected Object a1;   OwnerHistory - java inheritance - ENTITY IfcOwnerHistory
	// Name: protected String a2;   Name - java inheritance - STRING
	// Description: protected String a3;   Description - java inheritance - STRING
	// RelatedObjects: protected AIfcobjectdefinition a4;   RelatedObjects - java inheritance - SET OF ENTITY
	// RelatedObjectsType: protected int a5;   RelatedObjectsType - java inheritance - ENUMERATION IfcObjectTypeEnum
	protected Object a6; // RelatingProduct - current entity - SELECT IfcProductSelect
	protected static final jsdai.dictionary.CExplicit_attribute a6$ = CEntity.initExplicitAttribute(definition, 6);
*/

	/*----------------------------- Attributes (new version) -----------*/

	// GlobalId - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a0$ = CEntity.initExplicitAttribute(definition, 0);
	// protected String a0;
	// OwnerHistory - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a1$ = CEntity.initExplicitAttribute(definition, 1);
	// protected Object a1;
	// Name - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a2$ = CEntity.initExplicitAttribute(definition, 2);
	// protected String a2;
	// Description - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a3$ = CEntity.initExplicitAttribute(definition, 3);
	// protected String a3;
	// RelatedObjects - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a4$ = CEntity.initExplicitAttribute(definition, 4);
	// protected AIfcobjectdefinition a4;
	// RelatedObjectsType - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a5$ = CEntity.initExplicitAttribute(definition, 5);
	// protected int a5;
	// RelatingProduct - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a6$ = CEntity.initExplicitAttribute(definition, 6);
	protected Object a6;

	public jsdai.dictionary.EEntity_definition getInstanceType() {
		return definition;
	}

/* *** old implementation ***

	protected void changeReferences(InverseEntity old, InverseEntity newer) throws SdaiException {
		super.changeReferences(old, newer);
		if (a6 == old) {
			a6 = newer;
		}
	}
*/


	protected void changeReferences(InverseEntity old, InverseEntity newer) throws SdaiException {
		super.changeReferences(old, newer);
		if (a6 == old) {
			a6 = newer;
		}
	}

	/*----------- Methods for attribute access -----------*/


	/*----------- Methods for attribute access (new)-----------*/

	//going through all the attributes: #5618=EXPLICIT_ATTRIBUTE('GlobalId',#5616,0,#2517,$,.F.);
	//<01> generating methods for consolidated attribute:  GlobalId
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #5619=EXPLICIT_ATTRIBUTE('OwnerHistory',#5616,1,#4858,$,.T.);
	//<01> generating methods for consolidated attribute:  OwnerHistory
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	// attribute (java explicit): OwnerHistory, base type: entity IfcOwnerHistory
	public static int usedinOwnerhistory(EIfcroot type, EIfcownerhistory instance, ASdaiModel domain, AEntity result) throws SdaiException {
		return ((CEntity)instance).makeUsedin(definition, a1$, domain, result);
	}
	//going through all the attributes: #5620=EXPLICIT_ATTRIBUTE('Name',#5616,2,#2539,$,.T.);
	//<01> generating methods for consolidated attribute:  Name
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #5621=EXPLICIT_ATTRIBUTE('Description',#5616,3,#2657,$,.T.);
	//<01> generating methods for consolidated attribute:  Description
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #5350=EXPLICIT_ATTRIBUTE('RelatedObjects',#5348,0,#7075,$,.F.);
	//<01> generating methods for consolidated attribute:  RelatedObjects
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	// methods for attribute: RelatedObjects, base type: SET OF ENTITY
	public static int usedinRelatedobjects(EIfcrelassigns type, EIfcobjectdefinition instance, ASdaiModel domain, AEntity result) throws SdaiException {
		return ((CEntity)instance).makeUsedin(definition, a4$, domain, result);
	}
	//going through all the attributes: #5351=EXPLICIT_ATTRIBUTE('RelatedObjectsType',#5348,1,#2933,$,.T.);
	//<01> generating methods for consolidated attribute:  RelatedObjectsType
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #5371=EXPLICIT_ATTRIBUTE('RelatingProduct',#5369,0,#3183,$,.F.);
	//<01> generating methods for consolidated attribute:  RelatingProduct
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	// -2- methods for SELECT attribute: RelatingProduct
	public static int usedinRelatingproduct(EIfcrelassignstoproduct type, EEntity instance, ASdaiModel domain, AEntity result) throws SdaiException {
		return ((CEntity)instance).makeUsedin(definition, a6$, domain, result);
	}
	public boolean testRelatingproduct(EIfcrelassignstoproduct type) throws SdaiException {
		return test_instance(a6);
	}

	public EEntity getRelatingproduct(EIfcrelassignstoproduct type) throws SdaiException { // case 1
		return get_instance_select(a6);
	}

	public void setRelatingproduct(EIfcrelassignstoproduct type, EEntity value) throws SdaiException { // case 1
		a6 = set_instance(a6, value);
	}

	public void unsetRelatingproduct(EIfcrelassignstoproduct type) throws SdaiException {
		a6 = unset_instance(a6);
	}

	public static jsdai.dictionary.EAttribute attributeRelatingproduct(EIfcrelassignstoproduct type) throws SdaiException {
		return a6$;
	}


	/*---------------------- setAll() --------------------*/

/* *** old implementation ***
	protected void setAll(ComplexEntityValue av) throws SdaiException {
		if (av == null) {
			if (a4 instanceof CAggregate)
				a4.unsetAll();
			a4 = null;
			a5 = 0;
			a6 = unset_instance(a6);
			a0 = null;
			a1 = unset_instance(a1);
			a2 = null;
			a3 = null;
			return;
		}
		a4 = (AIfcobjectdefinition)av.entityValues[0].getInstanceAggregate(0, a4$, this);
		a5 = av.entityValues[0].getEnumeration(1, a5$);
		a6 = av.entityValues[1].getInstance(0, this, a6$);
		a0 = av.entityValues[3].getString(0);
		a1 = av.entityValues[3].getInstance(1, this, a1$);
		a2 = av.entityValues[3].getString(2);
		a3 = av.entityValues[3].getString(3);
	}
*/

	protected void setAll(ComplexEntityValue av) throws SdaiException {
		if (av == null) {
			if (a4 instanceof CAggregate)
				a4.unsetAll();
			a4 = null;
			a5 = 0;
			a6 = unset_instance(a6);
			a0 = null;
			a1 = unset_instance(a1);
			a2 = null;
			a3 = null;
			return;
		}
		a4 = (AIfcobjectdefinition)av.entityValues[0].getInstanceAggregate(0, a4$, this);
		a5 = av.entityValues[0].getEnumeration(1, a5$);
		a6 = av.entityValues[1].getInstance(0, this, a6$);
		a0 = av.entityValues[3].getString(0);
		a1 = av.entityValues[3].getInstance(1, this, a1$);
		a2 = av.entityValues[3].getString(2);
		a3 = av.entityValues[3].getString(3);
	}

	/*---------------------- getAll() --------------------*/

/* *** old implementation ***
	protected void getAll(ComplexEntityValue av) throws SdaiException {
		// partial entity: IfcRelAssigns
		av.entityValues[0].setInstanceAggregate(0, a4);
		av.entityValues[0].setEnumeration(1, a5, a5$);
		// partial entity: IfcRelAssignsToProduct
		av.entityValues[1].setInstance(0, a6);
		// partial entity: IfcRelationship
		// partial entity: IfcRoot
		av.entityValues[3].setString(0, a0);
		av.entityValues[3].setInstance(1, a1);
		av.entityValues[3].setString(2, a2);
		av.entityValues[3].setString(3, a3);
	}
*/

	protected void getAll(ComplexEntityValue av) throws SdaiException {
		// partial entity: IfcRelAssigns
		av.entityValues[0].setInstanceAggregate(0, a4);
		av.entityValues[0].setEnumeration(1, a5, a5$);
		// partial entity: IfcRelAssignsToProduct
		av.entityValues[1].setInstance(0, a6);
		// partial entity: IfcRelationship
		// partial entity: IfcRoot
		av.entityValues[3].setString(0, a0);
		av.entityValues[3].setInstance(1, a1);
		av.entityValues[3].setString(2, a2);
		av.entityValues[3].setString(3, a3);
	}

	/*---------------------- methods to validate WHERE rules --------------------*/

	public int rIfcrelassignstoproductNoselfreference(SdaiContext _context) throws SdaiException {
	




									
									Value _internal_aggregate_source222 = Value.alloc(jsdai.SIfc4.CIfcrelassignstoproduct.definition).set(_context, this).groupReference(_context, jsdai.SIfc4.CIfcrelassigns.class).getAttribute(jsdai.SIfc4.CIfcrelassigns.attributeRelatedobjects(null), _context);
									Value _result220 = Value.alloc(_internal_aggregate_source222).create();
									if (_internal_aggregate_source222.getActualJavaType() != Value.INDETERMINATE) {
										for (int _i221 = 1; _i221 <= _internal_aggregate_source222.getMemberCount(); _i221++) {
											Value _implicit_52_Temp = _internal_aggregate_source222.getByIndex(_i221);
											if (Value.alloc(ExpressTypes.LOGICAL_TYPE).instanceEqual(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcProductSelect).set(_context, get(a6$)), _implicit_52_Temp).getLogical() == 2) {
												_result220.addMember(_context, _implicit_52_Temp);
											} else
											if (_internal_aggregate_source222.getDeclaredType() instanceof jsdai.dictionary.EArray_type) {
												_implicit_52_Temp.unset();
												_result220.addMember(_context, _implicit_52_Temp);
											}
										}
									} else {
										_result220.unset();
									}
		return (Value.alloc(ExpressTypes.LOGICAL_TYPE).set(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).equal(_context, Value.alloc(ExpressTypes.INTEGER_TYPE).sizeOfExt0(_context, _result220), Value.alloc(ExpressTypes.INTEGER_TYPE).set(_context, 0))).getLogical());
	}
}
