/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing entity IfcCShapeProfileDef

package jsdai.SIfc4;
import jsdai.lang.*;

public class CIfccshapeprofiledef extends CIfcparameterizedprofiledef implements EIfccshapeprofiledef {
	public static final jsdai.dictionary.CEntity_definition definition = initEntityDefinition(CIfccshapeprofiledef.class, SIfc4.ss);

	/*----------------------------- Attributes -----------*/

/*
	// ProfileType: protected int a0;   ProfileType - java inheritance - ENUMERATION IfcProfileTypeEnum
	// ProfileName: protected String a1;   ProfileName - java inheritance - STRING
	// HasExternalReference: protected Object  - inverse - java inheritance -  ENTITY IfcExternalReferenceRelationship
	// HasProperties: protected Object  - inverse - java inheritance -  ENTITY IfcProfileProperties
	// Position: protected Object a2;   Position - java inheritance - ENTITY IfcAxis2Placement2D
	protected double a3; // Depth - current entity - REAL
	protected static final jsdai.dictionary.CExplicit_attribute a3$ = CEntity.initExplicitAttribute(definition, 3);
	protected double a4; // Width - current entity - REAL
	protected static final jsdai.dictionary.CExplicit_attribute a4$ = CEntity.initExplicitAttribute(definition, 4);
	protected double a5; // WallThickness - current entity - REAL
	protected static final jsdai.dictionary.CExplicit_attribute a5$ = CEntity.initExplicitAttribute(definition, 5);
	protected double a6; // Girth - current entity - REAL
	protected static final jsdai.dictionary.CExplicit_attribute a6$ = CEntity.initExplicitAttribute(definition, 6);
	protected double a7; // InternalFilletRadius - current entity - REAL
	protected static final jsdai.dictionary.CExplicit_attribute a7$ = CEntity.initExplicitAttribute(definition, 7);
*/

	/*----------------------------- Attributes (new version) -----------*/

	// ProfileType - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a0$ = CEntity.initExplicitAttribute(definition, 0);
	// protected int a0;
	// ProfileName - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a1$ = CEntity.initExplicitAttribute(definition, 1);
	// protected String a1;
	// HasExternalReference - inverse - java inheritance
	// protected static final jsdai.dictionary.CInverse_attribute i0$ = CEntity.initInverseAttribute(definition, 0);
	// HasProperties - inverse - java inheritance
	// protected static final jsdai.dictionary.CInverse_attribute i1$ = CEntity.initInverseAttribute(definition, 1);
	// Position - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a2$ = CEntity.initExplicitAttribute(definition, 2);
	// protected Object a2;
	// Depth - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a3$ = CEntity.initExplicitAttribute(definition, 3);
	protected double a3;
	// Width - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a4$ = CEntity.initExplicitAttribute(definition, 4);
	protected double a4;
	// WallThickness - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a5$ = CEntity.initExplicitAttribute(definition, 5);
	protected double a5;
	// Girth - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a6$ = CEntity.initExplicitAttribute(definition, 6);
	protected double a6;
	// InternalFilletRadius - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a7$ = CEntity.initExplicitAttribute(definition, 7);
	protected double a7;

	public jsdai.dictionary.EEntity_definition getInstanceType() {
		return definition;
	}

/* *** old implementation ***

	protected void changeReferences(InverseEntity old, InverseEntity newer) throws SdaiException {
		super.changeReferences(old, newer);
	}
*/


	protected void changeReferences(InverseEntity old, InverseEntity newer) throws SdaiException {
		super.changeReferences(old, newer);
	}

	/*----------- Methods for attribute access -----------*/


	/*----------- Methods for attribute access (new)-----------*/

	//going through all the attributes: #5070=EXPLICIT_ATTRIBUTE('ProfileType',#5068,0,#2963,$,.F.);
	//<01> generating methods for consolidated attribute:  ProfileType
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #5071=EXPLICIT_ATTRIBUTE('ProfileName',#5068,1,#2539,$,.T.);
	//<01> generating methods for consolidated attribute:  ProfileName
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #5072=INVERSE_ATTRIBUTE('HasExternalReference',#5068,0,#4231,$,#4234,#8892,$,.F.);
	//<01> generating methods for consolidated attribute:  HasExternalReference
	//<01-1> supertype, java inheritance
	//<01-1-2> inverse - generateInverseSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #5073=INVERSE_ATTRIBUTE('HasProperties',#5068,1,#5074,$,#5076,#8894,$,.F.);
	//<01> generating methods for consolidated attribute:  HasProperties
	//<01-1> supertype, java inheritance
	//<01-1-2> inverse - generateInverseSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #4870=EXPLICIT_ATTRIBUTE('Position',#4868,0,#3378,$,.T.);
	//<01> generating methods for consolidated attribute:  Position
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	// attribute (java explicit): Position, base type: entity IfcAxis2Placement2D
	public static int usedinPosition(EIfcparameterizedprofiledef type, EIfcaxis2placement2d instance, ASdaiModel domain, AEntity result) throws SdaiException {
		return ((CEntity)instance).makeUsedin(definition, a2$, domain, result);
	}
	//going through all the attributes: #3533=EXPLICIT_ATTRIBUTE('Depth',#3531,0,#2605,$,.F.);
	//<01> generating methods for consolidated attribute:  Depth
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	/// methods for attribute: Depth, base type: REAL
	public boolean testDepth(EIfccshapeprofiledef type) throws SdaiException {
		return test_double(a3);
	}
	public double getDepth(EIfccshapeprofiledef type) throws SdaiException {
		return get_double(a3);
	}
	public void setDepth(EIfccshapeprofiledef type, double value) throws SdaiException {
		a3 = set_double(value);
	}
	public void unsetDepth(EIfccshapeprofiledef type) throws SdaiException {
		a3 = unset_double();
	}
	public static jsdai.dictionary.EAttribute attributeDepth(EIfccshapeprofiledef type) throws SdaiException {
		return a3$;
	}

	//going through all the attributes: #3534=EXPLICIT_ATTRIBUTE('Width',#3531,1,#2605,$,.F.);
	//<01> generating methods for consolidated attribute:  Width
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	/// methods for attribute: Width, base type: REAL
	public boolean testWidth(EIfccshapeprofiledef type) throws SdaiException {
		return test_double(a4);
	}
	public double getWidth(EIfccshapeprofiledef type) throws SdaiException {
		return get_double(a4);
	}
	public void setWidth(EIfccshapeprofiledef type, double value) throws SdaiException {
		a4 = set_double(value);
	}
	public void unsetWidth(EIfccshapeprofiledef type) throws SdaiException {
		a4 = unset_double();
	}
	public static jsdai.dictionary.EAttribute attributeWidth(EIfccshapeprofiledef type) throws SdaiException {
		return a4$;
	}

	//going through all the attributes: #3535=EXPLICIT_ATTRIBUTE('WallThickness',#3531,2,#2605,$,.F.);
	//<01> generating methods for consolidated attribute:  WallThickness
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	/// methods for attribute: WallThickness, base type: REAL
	public boolean testWallthickness(EIfccshapeprofiledef type) throws SdaiException {
		return test_double(a5);
	}
	public double getWallthickness(EIfccshapeprofiledef type) throws SdaiException {
		return get_double(a5);
	}
	public void setWallthickness(EIfccshapeprofiledef type, double value) throws SdaiException {
		a5 = set_double(value);
	}
	public void unsetWallthickness(EIfccshapeprofiledef type) throws SdaiException {
		a5 = unset_double();
	}
	public static jsdai.dictionary.EAttribute attributeWallthickness(EIfccshapeprofiledef type) throws SdaiException {
		return a5$;
	}

	//going through all the attributes: #3536=EXPLICIT_ATTRIBUTE('Girth',#3531,3,#2605,$,.F.);
	//<01> generating methods for consolidated attribute:  Girth
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	/// methods for attribute: Girth, base type: REAL
	public boolean testGirth(EIfccshapeprofiledef type) throws SdaiException {
		return test_double(a6);
	}
	public double getGirth(EIfccshapeprofiledef type) throws SdaiException {
		return get_double(a6);
	}
	public void setGirth(EIfccshapeprofiledef type, double value) throws SdaiException {
		a6 = set_double(value);
	}
	public void unsetGirth(EIfccshapeprofiledef type) throws SdaiException {
		a6 = unset_double();
	}
	public static jsdai.dictionary.EAttribute attributeGirth(EIfccshapeprofiledef type) throws SdaiException {
		return a6$;
	}

	//going through all the attributes: #3537=EXPLICIT_ATTRIBUTE('InternalFilletRadius',#3531,4,#2591,$,.T.);
	//<01> generating methods for consolidated attribute:  InternalFilletRadius
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	/// methods for attribute: InternalFilletRadius, base type: REAL
	public boolean testInternalfilletradius(EIfccshapeprofiledef type) throws SdaiException {
		return test_double(a7);
	}
	public double getInternalfilletradius(EIfccshapeprofiledef type) throws SdaiException {
		return get_double(a7);
	}
	public void setInternalfilletradius(EIfccshapeprofiledef type, double value) throws SdaiException {
		a7 = set_double(value);
	}
	public void unsetInternalfilletradius(EIfccshapeprofiledef type) throws SdaiException {
		a7 = unset_double();
	}
	public static jsdai.dictionary.EAttribute attributeInternalfilletradius(EIfccshapeprofiledef type) throws SdaiException {
		return a7$;
	}


	/*---------------------- setAll() --------------------*/

/* *** old implementation ***
	protected void setAll(ComplexEntityValue av) throws SdaiException {
		if (av == null) {
			a3 = Double.NaN;
			a4 = Double.NaN;
			a5 = Double.NaN;
			a6 = Double.NaN;
			a7 = Double.NaN;
			a2 = unset_instance(a2);
			a0 = 0;
			a1 = null;
			return;
		}
		a3 = av.entityValues[0].getDouble(0);
		a4 = av.entityValues[0].getDouble(1);
		a5 = av.entityValues[0].getDouble(2);
		a6 = av.entityValues[0].getDouble(3);
		a7 = av.entityValues[0].getDouble(4);
		a2 = av.entityValues[1].getInstance(0, this, a2$);
		a0 = av.entityValues[2].getEnumeration(0, a0$);
		a1 = av.entityValues[2].getString(1);
	}
*/

	protected void setAll(ComplexEntityValue av) throws SdaiException {
		if (av == null) {
			a3 = Double.NaN;
			a4 = Double.NaN;
			a5 = Double.NaN;
			a6 = Double.NaN;
			a7 = Double.NaN;
			a2 = unset_instance(a2);
			a0 = 0;
			a1 = null;
			return;
		}
		a3 = av.entityValues[0].getDouble(0);
		a4 = av.entityValues[0].getDouble(1);
		a5 = av.entityValues[0].getDouble(2);
		a6 = av.entityValues[0].getDouble(3);
		a7 = av.entityValues[0].getDouble(4);
		a2 = av.entityValues[1].getInstance(0, this, a2$);
		a0 = av.entityValues[2].getEnumeration(0, a0$);
		a1 = av.entityValues[2].getString(1);
	}

	/*---------------------- getAll() --------------------*/

/* *** old implementation ***
	protected void getAll(ComplexEntityValue av) throws SdaiException {
		// partial entity: IfcCShapeProfileDef
		av.entityValues[0].setDouble(0, a3);
		av.entityValues[0].setDouble(1, a4);
		av.entityValues[0].setDouble(2, a5);
		av.entityValues[0].setDouble(3, a6);
		av.entityValues[0].setDouble(4, a7);
		// partial entity: IfcParameterizedProfileDef
		av.entityValues[1].setInstance(0, a2);
		// partial entity: IfcProfileDef
		av.entityValues[2].setEnumeration(0, a0, a0$);
		av.entityValues[2].setString(1, a1);
	}
*/

	protected void getAll(ComplexEntityValue av) throws SdaiException {
		// partial entity: IfcCShapeProfileDef
		av.entityValues[0].setDouble(0, a3);
		av.entityValues[0].setDouble(1, a4);
		av.entityValues[0].setDouble(2, a5);
		av.entityValues[0].setDouble(3, a6);
		av.entityValues[0].setDouble(4, a7);
		// partial entity: IfcParameterizedProfileDef
		av.entityValues[1].setInstance(0, a2);
		// partial entity: IfcProfileDef
		av.entityValues[2].setEnumeration(0, a0, a0$);
		av.entityValues[2].setString(1, a1);
	}

	/*---------------------- methods to validate WHERE rules --------------------*/

	public int rIfccshapeprofiledefValidgirth(SdaiContext _context) throws SdaiException {
	




		return (Value.alloc(ExpressTypes.LOGICAL_TYPE).set(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).less(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a6$)), Value.alloc(ExpressTypes.NUMBER_TYPE).divide(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a3$)), Value.alloc(ExpressTypes.REAL_TYPE).set(_context, 2.0)))).getLogical());
	}
	public int rIfccshapeprofiledefValidwallthickness(SdaiContext _context) throws SdaiException {
	






		return (Value.alloc(ExpressTypes.LOGICAL_TYPE).set(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).AND(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).less(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a5$)), Value.alloc(ExpressTypes.NUMBER_TYPE).divide(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a4$)), Value.alloc(ExpressTypes.REAL_TYPE).set(_context, 2.0))), Value.alloc(ExpressTypes.LOGICAL_TYPE).less(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a5$)), Value.alloc(ExpressTypes.NUMBER_TYPE).divide(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a3$)), Value.alloc(ExpressTypes.REAL_TYPE).set(_context, 2.0))))).getLogical());
	}
	public int rIfccshapeprofiledefValidinternalfilletradius(SdaiContext _context) throws SdaiException {
	









		return (Value.alloc(ExpressTypes.LOGICAL_TYPE).set(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).OR(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).NOT(Value.alloc(ExpressTypes.BOOLEAN_TYPE).exists(Value.alloc(jsdai.SIfc4.SIfc4._st_IfcNonNegativeLengthMeasure).set(_context, get(a7$)))), Value.alloc(ExpressTypes.LOGICAL_TYPE).AND(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).lequal(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcNonNegativeLengthMeasure).set(_context, get(a7$)), Value.alloc().substractOrDifference(_context, Value.alloc(ExpressTypes.NUMBER_TYPE).divide(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a4$)), Value.alloc(ExpressTypes.REAL_TYPE).set(_context, 2.0)), Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a5$)))), Value.alloc(ExpressTypes.LOGICAL_TYPE).lequal(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcNonNegativeLengthMeasure).set(_context, get(a7$)), Value.alloc().substractOrDifference(_context, Value.alloc(ExpressTypes.NUMBER_TYPE).divide(_context, Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a3$)), Value.alloc(ExpressTypes.REAL_TYPE).set(_context, 2.0)), Value.alloc(jsdai.SIfc4.SIfc4._st_IfcPositiveLengthMeasure).set(_context, get(a5$))))))).getLogical());
	}
}
