/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing entity IfcTelecomAddress

package jsdai.SIfc4;
import jsdai.lang.*;

public class CIfctelecomaddress extends CIfcaddress implements EIfctelecomaddress {
	public static final jsdai.dictionary.CEntity_definition definition = initEntityDefinition(CIfctelecomaddress.class, SIfc4.ss);

	/*----------------------------- Attributes -----------*/

/*
	// Purpose: protected int a0;   Purpose - java inheritance - ENUMERATION IfcAddressTypeEnum
	// Description: protected String a1;   Description - java inheritance - STRING
	// UserDefinedPurpose: protected String a2;   UserDefinedPurpose - java inheritance - STRING
	// OfPerson: protected Object  - inverse - java inheritance -  ENTITY IfcPerson
	// OfOrganization: protected Object  - inverse - java inheritance -  ENTITY IfcOrganization
	protected A_string a3; // TelephoneNumbers - current entity - LIST OF STRING
	protected static final jsdai.dictionary.CExplicit_attribute a3$ = CEntity.initExplicitAttribute(definition, 3);
	protected A_string a4; // FacsimileNumbers - current entity - LIST OF STRING
	protected static final jsdai.dictionary.CExplicit_attribute a4$ = CEntity.initExplicitAttribute(definition, 4);
	protected String a5; // PagerNumber - current entity - STRING
	protected static final jsdai.dictionary.CExplicit_attribute a5$ = CEntity.initExplicitAttribute(definition, 5);
	protected A_string a6; // ElectronicMailAddresses - current entity - LIST OF STRING
	protected static final jsdai.dictionary.CExplicit_attribute a6$ = CEntity.initExplicitAttribute(definition, 6);
	protected String a7; // WWWHomePageURL - current entity - STRING
	protected static final jsdai.dictionary.CExplicit_attribute a7$ = CEntity.initExplicitAttribute(definition, 7);
	protected A_string a8; // MessagingIDs - current entity - LIST OF STRING
	protected static final jsdai.dictionary.CExplicit_attribute a8$ = CEntity.initExplicitAttribute(definition, 8);
*/

	/*----------------------------- Attributes (new version) -----------*/

	// Purpose - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a0$ = CEntity.initExplicitAttribute(definition, 0);
	// protected int a0;
	// Description - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a1$ = CEntity.initExplicitAttribute(definition, 1);
	// protected String a1;
	// UserDefinedPurpose - explicit - java inheritance
	// protected static final jsdai.dictionary.CExplicit_attribute a2$ = CEntity.initExplicitAttribute(definition, 2);
	// protected String a2;
	// OfPerson - inverse - java inheritance
	// protected static final jsdai.dictionary.CInverse_attribute i0$ = CEntity.initInverseAttribute(definition, 0);
	// OfOrganization - inverse - java inheritance
	// protected static final jsdai.dictionary.CInverse_attribute i1$ = CEntity.initInverseAttribute(definition, 1);
	// TelephoneNumbers - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a3$ = CEntity.initExplicitAttribute(definition, 3);
	protected A_string a3;
	// FacsimileNumbers - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a4$ = CEntity.initExplicitAttribute(definition, 4);
	protected A_string a4;
	// PagerNumber - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a5$ = CEntity.initExplicitAttribute(definition, 5);
	protected String a5;
	// ElectronicMailAddresses - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a6$ = CEntity.initExplicitAttribute(definition, 6);
	protected A_string a6;
	// WWWHomePageURL - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a7$ = CEntity.initExplicitAttribute(definition, 7);
	protected String a7;
	// MessagingIDs - explicit - current entity
	protected static final jsdai.dictionary.CExplicit_attribute a8$ = CEntity.initExplicitAttribute(definition, 8);
	protected A_string a8;

	public jsdai.dictionary.EEntity_definition getInstanceType() {
		return definition;
	}

/* *** old implementation ***

	protected void changeReferences(InverseEntity old, InverseEntity newer) throws SdaiException {
		super.changeReferences(old, newer);
	}
*/


	protected void changeReferences(InverseEntity old, InverseEntity newer) throws SdaiException {
		super.changeReferences(old, newer);
	}

	/*----------- Methods for attribute access -----------*/


	/*----------- Methods for attribute access (new)-----------*/

	//going through all the attributes: #3252=EXPLICIT_ATTRIBUTE('Purpose',#3250,0,#2707,$,.T.);
	//<01> generating methods for consolidated attribute:  Purpose
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #3253=EXPLICIT_ATTRIBUTE('Description',#3250,1,#2657,$,.T.);
	//<01> generating methods for consolidated attribute:  Description
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #3254=EXPLICIT_ATTRIBUTE('UserDefinedPurpose',#3250,2,#2539,$,.T.);
	//<01> generating methods for consolidated attribute:  UserDefinedPurpose
	//<01-1> supertype, java inheritance
	//<01-1-0> explicit - generateExplicitSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #3255=INVERSE_ATTRIBUTE('OfPerson',#3250,0,#4894,$,#4903,#7536,$,.F.);
	//<01> generating methods for consolidated attribute:  OfPerson
	//<01-1> supertype, java inheritance
	//<01-1-2> inverse - generateInverseSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #3256=INVERSE_ATTRIBUTE('OfOrganization',#3250,1,#4830,$,#4836,#7538,$,.F.);
	//<01> generating methods for consolidated attribute:  OfOrganization
	//<01-1> supertype, java inheritance
	//<01-1-2> inverse - generateInverseSupertypeJavaInheritedMethodsX()
	//going through all the attributes: #6123=EXPLICIT_ATTRIBUTE('TelephoneNumbers',#6121,0,#7170,$,.T.);
	//<01> generating methods for consolidated attribute:  TelephoneNumbers
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	// methods for attribute: TelephoneNumbers, base type: LIST OF STRING
	public boolean testTelephonenumbers(EIfctelecomaddress type) throws SdaiException {
		return test_aggregate(a3);
	}
	public A_string getTelephonenumbers(EIfctelecomaddress type) throws SdaiException {
		return (A_string)get_aggregate(a3);
	}
	public A_string createTelephonenumbers(EIfctelecomaddress type) throws SdaiException {
		a3 = create_aggregate_string(a3, a3$, 0);
		return a3;
	}
	public void unsetTelephonenumbers(EIfctelecomaddress type) throws SdaiException {
		unset_aggregate(a3);
		a3 = null;
	}
	public static jsdai.dictionary.EAttribute attributeTelephonenumbers(EIfctelecomaddress type) throws SdaiException {
		return a3$;
	}

	//going through all the attributes: #6124=EXPLICIT_ATTRIBUTE('FacsimileNumbers',#6121,1,#7171,$,.T.);
	//<01> generating methods for consolidated attribute:  FacsimileNumbers
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	// methods for attribute: FacsimileNumbers, base type: LIST OF STRING
	public boolean testFacsimilenumbers(EIfctelecomaddress type) throws SdaiException {
		return test_aggregate(a4);
	}
	public A_string getFacsimilenumbers(EIfctelecomaddress type) throws SdaiException {
		return (A_string)get_aggregate(a4);
	}
	public A_string createFacsimilenumbers(EIfctelecomaddress type) throws SdaiException {
		a4 = create_aggregate_string(a4, a4$, 0);
		return a4;
	}
	public void unsetFacsimilenumbers(EIfctelecomaddress type) throws SdaiException {
		unset_aggregate(a4);
		a4 = null;
	}
	public static jsdai.dictionary.EAttribute attributeFacsimilenumbers(EIfctelecomaddress type) throws SdaiException {
		return a4$;
	}

	//going through all the attributes: #6125=EXPLICIT_ATTRIBUTE('PagerNumber',#6121,2,#2539,$,.T.);
	//<01> generating methods for consolidated attribute:  PagerNumber
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	/// methods for attribute: PagerNumber, base type: STRING
	public boolean testPagernumber(EIfctelecomaddress type) throws SdaiException {
		return test_string(a5);
	}
	public String getPagernumber(EIfctelecomaddress type) throws SdaiException {
		return get_string(a5);
	}
	public void setPagernumber(EIfctelecomaddress type, String value) throws SdaiException {
		a5 = set_string(value);
	}
	public void unsetPagernumber(EIfctelecomaddress type) throws SdaiException {
		a5 = unset_string();
	}
	public static jsdai.dictionary.EAttribute attributePagernumber(EIfctelecomaddress type) throws SdaiException {
		return a5$;
	}

	//going through all the attributes: #6126=EXPLICIT_ATTRIBUTE('ElectronicMailAddresses',#6121,3,#7172,$,.T.);
	//<01> generating methods for consolidated attribute:  ElectronicMailAddresses
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	// methods for attribute: ElectronicMailAddresses, base type: LIST OF STRING
	public boolean testElectronicmailaddresses(EIfctelecomaddress type) throws SdaiException {
		return test_aggregate(a6);
	}
	public A_string getElectronicmailaddresses(EIfctelecomaddress type) throws SdaiException {
		return (A_string)get_aggregate(a6);
	}
	public A_string createElectronicmailaddresses(EIfctelecomaddress type) throws SdaiException {
		a6 = create_aggregate_string(a6, a6$, 0);
		return a6;
	}
	public void unsetElectronicmailaddresses(EIfctelecomaddress type) throws SdaiException {
		unset_aggregate(a6);
		a6 = null;
	}
	public static jsdai.dictionary.EAttribute attributeElectronicmailaddresses(EIfctelecomaddress type) throws SdaiException {
		return a6$;
	}

	//going through all the attributes: #6127=EXPLICIT_ATTRIBUTE('WWWHomePageURL',#6121,4,#2687,$,.T.);
	//<01> generating methods for consolidated attribute:  WWWHomePageURL
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	/// methods for attribute: WWWHomePageURL, base type: STRING
	public boolean testWwwhomepageurl(EIfctelecomaddress type) throws SdaiException {
		return test_string(a7);
	}
	public String getWwwhomepageurl(EIfctelecomaddress type) throws SdaiException {
		return get_string(a7);
	}
	public void setWwwhomepageurl(EIfctelecomaddress type, String value) throws SdaiException {
		a7 = set_string(value);
	}
	public void unsetWwwhomepageurl(EIfctelecomaddress type) throws SdaiException {
		a7 = unset_string();
	}
	public static jsdai.dictionary.EAttribute attributeWwwhomepageurl(EIfctelecomaddress type) throws SdaiException {
		return a7$;
	}

	//going through all the attributes: #6128=EXPLICIT_ATTRIBUTE('MessagingIDs',#6121,5,#7173,$,.T.);
	//<01> generating methods for consolidated attribute:  MessagingIDs
	//<01-0> current entity
	//<01-0-0> explicit attribute - generateExplicitCurrentEntityMethodsX()
	// methods for attribute: MessagingIDs, base type: LIST OF STRING
	public boolean testMessagingids(EIfctelecomaddress type) throws SdaiException {
		return test_aggregate(a8);
	}
	public A_string getMessagingids(EIfctelecomaddress type) throws SdaiException {
		return (A_string)get_aggregate(a8);
	}
	public A_string createMessagingids(EIfctelecomaddress type) throws SdaiException {
		a8 = create_aggregate_string(a8, a8$, 0);
		return a8;
	}
	public void unsetMessagingids(EIfctelecomaddress type) throws SdaiException {
		unset_aggregate(a8);
		a8 = null;
	}
	public static jsdai.dictionary.EAttribute attributeMessagingids(EIfctelecomaddress type) throws SdaiException {
		return a8$;
	}


	/*---------------------- setAll() --------------------*/

/* *** old implementation ***
	protected void setAll(ComplexEntityValue av) throws SdaiException {
		if (av == null) {
			a0 = 0;
			a1 = null;
			a2 = null;
			if (a3 instanceof CAggregate)
				a3.unsetAll();
			a3 = null;
			if (a4 instanceof CAggregate)
				a4.unsetAll();
			a4 = null;
			a5 = null;
			if (a6 instanceof CAggregate)
				a6.unsetAll();
			a6 = null;
			a7 = null;
			if (a8 instanceof CAggregate)
				a8.unsetAll();
			a8 = null;
			return;
		}
		a0 = av.entityValues[0].getEnumeration(0, a0$);
		a1 = av.entityValues[0].getString(1);
		a2 = av.entityValues[0].getString(2);
		a3 = av.entityValues[1].getStringAggregate(0, a3$, this);
		a4 = av.entityValues[1].getStringAggregate(1, a4$, this);
		a5 = av.entityValues[1].getString(2);
		a6 = av.entityValues[1].getStringAggregate(3, a6$, this);
		a7 = av.entityValues[1].getString(4);
		a8 = av.entityValues[1].getStringAggregate(5, a8$, this);
	}
*/

	protected void setAll(ComplexEntityValue av) throws SdaiException {
		if (av == null) {
			a0 = 0;
			a1 = null;
			a2 = null;
			if (a3 instanceof CAggregate)
				a3.unsetAll();
			a3 = null;
			if (a4 instanceof CAggregate)
				a4.unsetAll();
			a4 = null;
			a5 = null;
			if (a6 instanceof CAggregate)
				a6.unsetAll();
			a6 = null;
			a7 = null;
			if (a8 instanceof CAggregate)
				a8.unsetAll();
			a8 = null;
			return;
		}
		a0 = av.entityValues[0].getEnumeration(0, a0$);
		a1 = av.entityValues[0].getString(1);
		a2 = av.entityValues[0].getString(2);
		a3 = av.entityValues[1].getStringAggregate(0, a3$, this);
		a4 = av.entityValues[1].getStringAggregate(1, a4$, this);
		a5 = av.entityValues[1].getString(2);
		a6 = av.entityValues[1].getStringAggregate(3, a6$, this);
		a7 = av.entityValues[1].getString(4);
		a8 = av.entityValues[1].getStringAggregate(5, a8$, this);
	}

	/*---------------------- getAll() --------------------*/

/* *** old implementation ***
	protected void getAll(ComplexEntityValue av) throws SdaiException {
		// partial entity: IfcAddress
		av.entityValues[0].setEnumeration(0, a0, a0$);
		av.entityValues[0].setString(1, a1);
		av.entityValues[0].setString(2, a2);
		// partial entity: IfcTelecomAddress
		av.entityValues[1].setStringAggregate(0, a3);
		av.entityValues[1].setStringAggregate(1, a4);
		av.entityValues[1].setString(2, a5);
		av.entityValues[1].setStringAggregate(3, a6);
		av.entityValues[1].setString(4, a7);
		av.entityValues[1].setStringAggregate(5, a8);
	}
*/

	protected void getAll(ComplexEntityValue av) throws SdaiException {
		// partial entity: IfcAddress
		av.entityValues[0].setEnumeration(0, a0, a0$);
		av.entityValues[0].setString(1, a1);
		av.entityValues[0].setString(2, a2);
		// partial entity: IfcTelecomAddress
		av.entityValues[1].setStringAggregate(0, a3);
		av.entityValues[1].setStringAggregate(1, a4);
		av.entityValues[1].setString(2, a5);
		av.entityValues[1].setStringAggregate(3, a6);
		av.entityValues[1].setString(4, a7);
		av.entityValues[1].setStringAggregate(5, a8);
	}

	/*---------------------- methods to validate WHERE rules --------------------*/

	public int rIfctelecomaddressMinimumdataprovided(SdaiContext _context) throws SdaiException {
	








		return (Value.alloc(ExpressTypes.LOGICAL_TYPE).set(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).OR(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).OR(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).OR(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).OR(_context, Value.alloc(ExpressTypes.LOGICAL_TYPE).OR(_context, Value.alloc(ExpressTypes.BOOLEAN_TYPE).exists(Value.alloc(jsdai.SIfc4.SIfc4._st_list_1_ifclabel).set(_context, get(a3$))), Value.alloc(ExpressTypes.BOOLEAN_TYPE).exists(Value.alloc(jsdai.SIfc4.SIfc4._st_list_1_ifclabel).set(_context, get(a4$)))), Value.alloc(ExpressTypes.BOOLEAN_TYPE).exists(Value.alloc(jsdai.SIfc4.SIfc4._st_IfcLabel).set(_context, get(a5$)))), Value.alloc(ExpressTypes.BOOLEAN_TYPE).exists(Value.alloc(jsdai.SIfc4.SIfc4._st_list_1_ifclabel).set(_context, get(a6$)))), Value.alloc(ExpressTypes.BOOLEAN_TYPE).exists(Value.alloc(jsdai.SIfc4.SIfc4._st_IfcURIReference).set(_context, get(a7$)))), Value.alloc(ExpressTypes.BOOLEAN_TYPE).exists(Value.alloc(jsdai.SIfc4.SIfc4._st_list_1_ifcurireference).set(_context, get(a8$))))).getLogical());
	}
}
