/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRoundedRectangleProfileDef

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcroundedrectangleprofiledef extends EIfcrectangleprofiledef {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:RoundingRadius, base type: REAL
	public boolean testRoundingradius(EIfcroundedrectangleprofiledef type) throws SdaiException;
	public double getRoundingradius(EIfcroundedrectangleprofiledef type) throws SdaiException;
	public void setRoundingradius(EIfcroundedrectangleprofiledef type, double value) throws SdaiException;
	public void unsetRoundingradius(EIfcroundedrectangleprofiledef type) throws SdaiException;

}
