/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcEllipse

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcellipse extends EIfcconic {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:SemiAxis1, base type: REAL
	public boolean testSemiaxis1(EIfcellipse type) throws SdaiException;
	public double getSemiaxis1(EIfcellipse type) throws SdaiException;
	public void setSemiaxis1(EIfcellipse type, double value) throws SdaiException;
	public void unsetSemiaxis1(EIfcellipse type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:SemiAxis2, base type: REAL
	public boolean testSemiaxis2(EIfcellipse type) throws SdaiException;
	public double getSemiaxis2(EIfcellipse type) throws SdaiException;
	public void setSemiaxis2(EIfcellipse type, double value) throws SdaiException;
	public void unsetSemiaxis2(EIfcellipse type) throws SdaiException;

}
