/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcElementarySurface

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcelementarysurface extends EIfcsurface {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:Position, base type: entity IfcAxis2Placement3D
	public boolean testPosition(EIfcelementarysurface type) throws SdaiException;
	public EIfcaxis2placement3d getPosition(EIfcelementarysurface type) throws SdaiException;
	public void setPosition(EIfcelementarysurface type, EIfcaxis2placement3d value) throws SdaiException;
	public void unsetPosition(EIfcelementarysurface type) throws SdaiException;

}
