/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcCircle

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfccircle extends EIfcconic {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Radius, base type: REAL
	public boolean testRadius(EIfccircle type) throws SdaiException;
	public double getRadius(EIfccircle type) throws SdaiException;
	public void setRadius(EIfccircle type, double value) throws SdaiException;
	public void unsetRadius(EIfccircle type) throws SdaiException;

}
