/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcCompositeProfileDef

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfccompositeprofiledef extends EIfcprofiledef {

	// generateExplicitAttributeMethodDeclarations: 1
	// methods for attribute: Profiles, base type: SET OF ENTITY
	public boolean testProfiles(EIfccompositeprofiledef type) throws SdaiException;
	public AIfcprofiledef getProfiles(EIfccompositeprofiledef type) throws SdaiException;
	public AIfcprofiledef createProfiles(EIfccompositeprofiledef type) throws SdaiException;
	public void unsetProfiles(EIfccompositeprofiledef type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Label, base type: STRING
	public boolean testLabel(EIfccompositeprofiledef type) throws SdaiException;
	public String getLabel(EIfccompositeprofiledef type) throws SdaiException;
	public void setLabel(EIfccompositeprofiledef type, String value) throws SdaiException;
	public void unsetLabel(EIfccompositeprofiledef type) throws SdaiException;

}
