/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcQuantitySet

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcquantityset extends EIfcpropertysetdefinition {

}
