/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcMaterialRelationship

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcmaterialrelationship extends EIfcresourcelevelrelationship {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:RelatingMaterial, base type: entity IfcMaterial
	public boolean testRelatingmaterial(EIfcmaterialrelationship type) throws SdaiException;
	public EIfcmaterial getRelatingmaterial(EIfcmaterialrelationship type) throws SdaiException;
	public void setRelatingmaterial(EIfcmaterialrelationship type, EIfcmaterial value) throws SdaiException;
	public void unsetRelatingmaterial(EIfcmaterialrelationship type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// methods for attribute: RelatedMaterials, base type: SET OF ENTITY
	public boolean testRelatedmaterials(EIfcmaterialrelationship type) throws SdaiException;
	public AIfcmaterial getRelatedmaterials(EIfcmaterialrelationship type) throws SdaiException;
	public AIfcmaterial createRelatedmaterials(EIfcmaterialrelationship type) throws SdaiException;
	public void unsetRelatedmaterials(EIfcmaterialrelationship type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Expression, base type: STRING
	public boolean testExpression(EIfcmaterialrelationship type) throws SdaiException;
	public String getExpression(EIfcmaterialrelationship type) throws SdaiException;
	public void setExpression(EIfcmaterialrelationship type, String value) throws SdaiException;
	public void unsetExpression(EIfcmaterialrelationship type) throws SdaiException;

}
