/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcStackTerminalType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcstackterminaltype extends EIfcflowterminaltype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcstackterminaltype type) throws SdaiException;
	public int getPredefinedtype(EIfcstackterminaltype type) throws SdaiException;
	public void setPredefinedtype(EIfcstackterminaltype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcstackterminaltype type) throws SdaiException;

}
