/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcCoolingTowerType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfccoolingtowertype extends EIfcenergyconversiondevicetype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfccoolingtowertype type) throws SdaiException;
	public int getPredefinedtype(EIfccoolingtowertype type) throws SdaiException;
	public void setPredefinedtype(EIfccoolingtowertype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfccoolingtowertype type) throws SdaiException;

}
