/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcCableCarrierSegment

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfccablecarriersegment extends EIfcflowsegment {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfccablecarriersegment type) throws SdaiException;
	public int getPredefinedtype(EIfccablecarriersegment type) throws SdaiException;
	public void setPredefinedtype(EIfccablecarriersegment type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfccablecarriersegment type) throws SdaiException;

}
