/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRelAssignsToProduct

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcrelassignstoproduct extends EIfcrelassigns {

	// generateExplicitAttributeMethodDeclarations: 1
	// constants and methods for SELECT attribute: RelatingProduct
	boolean testRelatingproduct(EIfcrelassignstoproduct type) throws SdaiException;

	EEntity getRelatingproduct(EIfcrelassignstoproduct type) throws SdaiException; // case 1

	void setRelatingproduct(EIfcrelassignstoproduct type, EEntity value) throws SdaiException; // case 1

	void unsetRelatingproduct(EIfcrelassignstoproduct type) throws SdaiException;

}
