/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcUnitaryControlElementType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcunitarycontrolelementtype extends EIfcdistributioncontrolelementtype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcunitarycontrolelementtype type) throws SdaiException;
	public int getPredefinedtype(EIfcunitarycontrolelementtype type) throws SdaiException;
	public void setPredefinedtype(EIfcunitarycontrolelementtype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcunitarycontrolelementtype type) throws SdaiException;

}
