/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcSurface

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcsurface extends EIfcgeometricrepresentationitem {

	// generateDerivedAttributeMethodDeclarations: 1
	/// methods for derived attribute:Dim, base type: INTEGER
	public boolean testDim(EIfcsurface type) throws SdaiException;
	public int getDim(EIfcsurface type) throws SdaiException;
	public Value getDim(EIfcsurface type, SdaiContext _context) throws SdaiException;

}
