/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcZone

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfczone extends EIfcsystem {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:LongName, base type: STRING
	public boolean testLongname(EIfczone type) throws SdaiException;
	public String getLongname(EIfczone type) throws SdaiException;
	public void setLongname(EIfczone type, String value) throws SdaiException;
	public void unsetLongname(EIfczone type) throws SdaiException;

}
