/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcEngineType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcenginetype extends EIfcenergyconversiondevicetype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcenginetype type) throws SdaiException;
	public int getPredefinedtype(EIfcenginetype type) throws SdaiException;
	public void setPredefinedtype(EIfcenginetype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcenginetype type) throws SdaiException;

}
