/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcSolarDevice

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcsolardevice extends EIfcenergyconversiondevice {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcsolardevice type) throws SdaiException;
	public int getPredefinedtype(EIfcsolardevice type) throws SdaiException;
	public void setPredefinedtype(EIfcsolardevice type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcsolardevice type) throws SdaiException;

}
