/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRelSpaceBoundary1stLevel

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcrelspaceboundary1stlevel extends EIfcrelspaceboundary {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:ParentBoundary, base type: entity IfcRelSpaceBoundary1stLevel
	public boolean testParentboundary(EIfcrelspaceboundary1stlevel type) throws SdaiException;
	public EIfcrelspaceboundary1stlevel getParentboundary(EIfcrelspaceboundary1stlevel type) throws SdaiException;
	public void setParentboundary(EIfcrelspaceboundary1stlevel type, EIfcrelspaceboundary1stlevel value) throws SdaiException;
	public void unsetParentboundary(EIfcrelspaceboundary1stlevel type) throws SdaiException;

	// Inverse attribute - InnerBoundaries : SET[0:-2147483648] OF IfcRelSpaceBoundary1stLevel FOR ParentBoundary
	public AIfcrelspaceboundary1stlevel getInnerboundaries(EIfcrelspaceboundary1stlevel type, ASdaiModel domain) throws SdaiException;
}
