/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcElectricTimeControlType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcelectrictimecontroltype extends EIfcflowcontrollertype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcelectrictimecontroltype type) throws SdaiException;
	public int getPredefinedtype(EIfcelectrictimecontroltype type) throws SdaiException;
	public void setPredefinedtype(EIfcelectrictimecontroltype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcelectrictimecontroltype type) throws SdaiException;

}
