/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcFooting

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcfooting extends EIfcbuildingelement {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcfooting type) throws SdaiException;
	public int getPredefinedtype(EIfcfooting type) throws SdaiException;
	public void setPredefinedtype(EIfcfooting type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcfooting type) throws SdaiException;

}
