/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcWall

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcwall extends EIfcbuildingelement {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcwall type) throws SdaiException;
	public int getPredefinedtype(EIfcwall type) throws SdaiException;
	public void setPredefinedtype(EIfcwall type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcwall type) throws SdaiException;

}
