/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcMaterialLayer

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcmateriallayer extends EIfcmaterialdefinition {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:Material, base type: entity IfcMaterial
	public boolean testMaterial(EIfcmateriallayer type) throws SdaiException;
	public EIfcmaterial getMaterial(EIfcmateriallayer type) throws SdaiException;
	public void setMaterial(EIfcmateriallayer type, EIfcmaterial value) throws SdaiException;
	public void unsetMaterial(EIfcmateriallayer type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:LayerThickness, base type: REAL
	public boolean testLayerthickness(EIfcmateriallayer type) throws SdaiException;
	public double getLayerthickness(EIfcmateriallayer type) throws SdaiException;
	public void setLayerthickness(EIfcmateriallayer type, double value) throws SdaiException;
	public void unsetLayerthickness(EIfcmateriallayer type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:IsVentilated, base type: LOGICAL
	public boolean testIsventilated(EIfcmateriallayer type) throws SdaiException;
	public int getIsventilated(EIfcmateriallayer type) throws SdaiException;
	public void setIsventilated(EIfcmateriallayer type, int value) throws SdaiException;
	public void unsetIsventilated(EIfcmateriallayer type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Name, base type: STRING
	public boolean testName(EIfcmateriallayer type) throws SdaiException;
	public String getName(EIfcmateriallayer type) throws SdaiException;
	public void setName(EIfcmateriallayer type, String value) throws SdaiException;
	public void unsetName(EIfcmateriallayer type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Description, base type: STRING
	public boolean testDescription(EIfcmateriallayer type) throws SdaiException;
	public String getDescription(EIfcmateriallayer type) throws SdaiException;
	public void setDescription(EIfcmateriallayer type, String value) throws SdaiException;
	public void unsetDescription(EIfcmateriallayer type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Category, base type: STRING
	public boolean testCategory(EIfcmateriallayer type) throws SdaiException;
	public String getCategory(EIfcmateriallayer type) throws SdaiException;
	public void setCategory(EIfcmateriallayer type, String value) throws SdaiException;
	public void unsetCategory(EIfcmateriallayer type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Priority, base type: REAL
	public boolean testPriority(EIfcmateriallayer type) throws SdaiException;
	public double getPriority(EIfcmateriallayer type) throws SdaiException;
	public void setPriority(EIfcmateriallayer type, double value) throws SdaiException;
	public void unsetPriority(EIfcmateriallayer type) throws SdaiException;

	// Inverse attribute - ToMaterialLayerSet : IfcMaterialLayerSet FOR MaterialLayers
	public AIfcmateriallayerset getTomateriallayerset(EIfcmateriallayer type, ASdaiModel domain) throws SdaiException;
}
