/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcGeometricSet

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcgeometricset extends EIfcgeometricrepresentationitem {

	// generateExplicitAttributeMethodDeclarations: 1
	// methods for attribute: Elements, base type: SET OF SELECT
	public boolean testElements(EIfcgeometricset type) throws SdaiException;
	public AIfcgeometricsetselect getElements(EIfcgeometricset type) throws SdaiException;
	public AIfcgeometricsetselect createElements(EIfcgeometricset type) throws SdaiException;
	public void unsetElements(EIfcgeometricset type) throws SdaiException;

	// generateDerivedAttributeMethodDeclarations: 1
	/// methods for derived attribute:Dim, base type: INTEGER
	public boolean testDim(EIfcgeometricset type) throws SdaiException;
	public int getDim(EIfcgeometricset type) throws SdaiException;
	public Value getDim(EIfcgeometricset type, SdaiContext _context) throws SdaiException;

}
