/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcUnitAssignment

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcunitassignment extends EEntity {

	// generateExplicitAttributeMethodDeclarations: 1
	// methods for attribute: Units, base type: SET OF SELECT
	public boolean testUnits(EIfcunitassignment type) throws SdaiException;
	public AIfcunit getUnits(EIfcunitassignment type) throws SdaiException;
	public AIfcunit createUnits(EIfcunitassignment type) throws SdaiException;
	public void unsetUnits(EIfcunitassignment type) throws SdaiException;

}
