/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcStructuralCurveAction

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcstructuralcurveaction extends EIfcstructuralaction {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:ProjectedOrTrue, base type: ENUMERATION
	public boolean testProjectedortrue(EIfcstructuralcurveaction type) throws SdaiException;
	public int getProjectedortrue(EIfcstructuralcurveaction type) throws SdaiException;
	public void setProjectedortrue(EIfcstructuralcurveaction type, int value) throws SdaiException;
	public void unsetProjectedortrue(EIfcstructuralcurveaction type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcstructuralcurveaction type) throws SdaiException;
	public int getPredefinedtype(EIfcstructuralcurveaction type) throws SdaiException;
	public void setPredefinedtype(EIfcstructuralcurveaction type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcstructuralcurveaction type) throws SdaiException;

}
