/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing enumeration IfcSequenceEnum

package jsdai.SIfc4;
import jsdai.lang.*;

public class EIfcsequenceenum {

	private static final int unset = 0;
	public static final int START_START = 1;	// START_START
	public static final int START_FINISH = 2;	// START_FINISH
	public static final int FINISH_START = 3;	// FINISH_START
	public static final int FINISH_FINISH = 4;	// FINISH_FINISH
	public static final int USERDEFINED = 5;	// USERDEFINED
	public static final int NOTDEFINED = 6;	// NOTDEFINED

	private static final int dim = 6;

	public static final String values[] = {"START_START", "START_FINISH", "FINISH_START", "FINISH_FINISH", "USERDEFINED", "NOTDEFINED"};

//-------- methods ---------

	private static boolean isSet(int value) { return ((value >= 1) && (value <= dim)); }

	public static int toInt(String str) {
		for (int i = 0; i < dim; i++) {
			if (values[i].equalsIgnoreCase(str)) return i+1;
		}
		return unset;
	}

	public static String toString(int value) {
		if (!isSet(value)) return "unset";
		return values[value-1];
	}
}
