/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcConstructionEquipmentResourceType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcconstructionequipmentresourcetype extends EIfcconstructionresourcetype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcconstructionequipmentresourcetype type) throws SdaiException;
	public int getPredefinedtype(EIfcconstructionequipmentresourcetype type) throws SdaiException;
	public void setPredefinedtype(EIfcconstructionequipmentresourcetype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcconstructionequipmentresourcetype type) throws SdaiException;

}
