/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcSwitchingDevice

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcswitchingdevice extends EIfcflowcontroller {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcswitchingdevice type) throws SdaiException;
	public int getPredefinedtype(EIfcswitchingdevice type) throws SdaiException;
	public void setPredefinedtype(EIfcswitchingdevice type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcswitchingdevice type) throws SdaiException;

}
