/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcPolygonalBoundedHalfSpace

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcpolygonalboundedhalfspace extends EIfchalfspacesolid {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:Position, base type: entity IfcAxis2Placement3D
	public boolean testPosition(EIfcpolygonalboundedhalfspace type) throws SdaiException;
	public EIfcaxis2placement3d getPosition(EIfcpolygonalboundedhalfspace type) throws SdaiException;
	public void setPosition(EIfcpolygonalboundedhalfspace type, EIfcaxis2placement3d value) throws SdaiException;
	public void unsetPosition(EIfcpolygonalboundedhalfspace type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PolygonalBoundary, base type: entity IfcBoundedCurve
	public boolean testPolygonalboundary(EIfcpolygonalboundedhalfspace type) throws SdaiException;
	public EIfcboundedcurve getPolygonalboundary(EIfcpolygonalboundedhalfspace type) throws SdaiException;
	public void setPolygonalboundary(EIfcpolygonalboundedhalfspace type, EIfcboundedcurve value) throws SdaiException;
	public void unsetPolygonalboundary(EIfcpolygonalboundedhalfspace type) throws SdaiException;

}
