/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcReinforcementDefinitionProperties

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcreinforcementdefinitionproperties extends EIfcpredefinedpropertyset {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:DefinitionType, base type: STRING
	public boolean testDefinitiontype(EIfcreinforcementdefinitionproperties type) throws SdaiException;
	public String getDefinitiontype(EIfcreinforcementdefinitionproperties type) throws SdaiException;
	public void setDefinitiontype(EIfcreinforcementdefinitionproperties type, String value) throws SdaiException;
	public void unsetDefinitiontype(EIfcreinforcementdefinitionproperties type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// methods for attribute: ReinforcementSectionDefinitions, base type: LIST OF ENTITY
	public boolean testReinforcementsectiondefinitions(EIfcreinforcementdefinitionproperties type) throws SdaiException;
	public AIfcsectionreinforcementproperties getReinforcementsectiondefinitions(EIfcreinforcementdefinitionproperties type) throws SdaiException;
	public AIfcsectionreinforcementproperties createReinforcementsectiondefinitions(EIfcreinforcementdefinitionproperties type) throws SdaiException;
	public void unsetReinforcementsectiondefinitions(EIfcreinforcementdefinitionproperties type) throws SdaiException;

}
