/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcPipeFitting

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcpipefitting extends EIfcflowfitting {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcpipefitting type) throws SdaiException;
	public int getPredefinedtype(EIfcpipefitting type) throws SdaiException;
	public void setPredefinedtype(EIfcpipefitting type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcpipefitting type) throws SdaiException;

}
