/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcFurniture

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcfurniture extends EIfcfurnishingelement {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcfurniture type) throws SdaiException;
	public int getPredefinedtype(EIfcfurniture type) throws SdaiException;
	public void setPredefinedtype(EIfcfurniture type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcfurniture type) throws SdaiException;

}
