/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcDuctSilencerType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcductsilencertype extends EIfcflowtreatmentdevicetype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcductsilencertype type) throws SdaiException;
	public int getPredefinedtype(EIfcductsilencertype type) throws SdaiException;
	public void setPredefinedtype(EIfcductsilencertype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcductsilencertype type) throws SdaiException;

}
