/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRelDefinesByProperties

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcreldefinesbyproperties extends EIfcreldefines {

	// generateExplicitAttributeMethodDeclarations: 1
	// methods for attribute: RelatedObjects, base type: SET OF ENTITY
	public boolean testRelatedobjects(EIfcreldefinesbyproperties type) throws SdaiException;
	public AIfcobjectdefinition getRelatedobjects(EIfcreldefinesbyproperties type) throws SdaiException;
	public AIfcobjectdefinition createRelatedobjects(EIfcreldefinesbyproperties type) throws SdaiException;
	public void unsetRelatedobjects(EIfcreldefinesbyproperties type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// constants and methods for SELECT attribute: RelatingPropertyDefinition
	int sRelatingpropertydefinitionIfcpropertysetdefinitionset = 2;

	int testRelatingpropertydefinition(EIfcreldefinesbyproperties type) throws SdaiException;

	EEntity getRelatingpropertydefinition(EIfcreldefinesbyproperties type) throws SdaiException; // case 1
	AIfcpropertysetdefinition getRelatingpropertydefinition(EIfcreldefinesbyproperties type, EIfcpropertysetdefinitionset node1) throws SdaiException; // case 2

	void setRelatingpropertydefinition(EIfcreldefinesbyproperties type, EEntity value) throws SdaiException; // case 1
	AIfcpropertysetdefinition createRelatingpropertydefinition(EIfcreldefinesbyproperties type, EIfcpropertysetdefinitionset node1) throws SdaiException; // case 2

	void unsetRelatingpropertydefinition(EIfcreldefinesbyproperties type) throws SdaiException;

}
