/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing enumeration IfcPileConstructionEnum

package jsdai.SIfc4;
import jsdai.lang.*;

public class EIfcpileconstructionenum {

	private static final int unset = 0;
	public static final int CAST_IN_PLACE = 1;	// CAST_IN_PLACE
	public static final int COMPOSITE = 2;	// COMPOSITE
	public static final int PRECAST_CONCRETE = 3;	// PRECAST_CONCRETE
	public static final int PREFAB_STEEL = 4;	// PREFAB_STEEL
	public static final int USERDEFINED = 5;	// USERDEFINED
	public static final int NOTDEFINED = 6;	// NOTDEFINED

	private static final int dim = 6;

	public static final String values[] = {"CAST_IN_PLACE", "COMPOSITE", "PRECAST_CONCRETE", "PREFAB_STEEL", "USERDEFINED", "NOTDEFINED"};

//-------- methods ---------

	private static boolean isSet(int value) { return ((value >= 1) && (value <= dim)); }

	public static int toInt(String str) {
		for (int i = 0; i < dim; i++) {
			if (values[i].equalsIgnoreCase(str)) return i+1;
		}
		return unset;
	}

	public static String toString(int value) {
		if (!isSet(value)) return "unset";
		return values[value-1];
	}
}
