/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRelConnectsStructuralActivity

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcrelconnectsstructuralactivity extends EIfcrelconnects {

	// generateExplicitAttributeMethodDeclarations: 1
	// constants and methods for SELECT attribute: RelatingElement
	boolean testRelatingelement(EIfcrelconnectsstructuralactivity type) throws SdaiException;

	EEntity getRelatingelement(EIfcrelconnectsstructuralactivity type) throws SdaiException; // case 1

	void setRelatingelement(EIfcrelconnectsstructuralactivity type, EEntity value) throws SdaiException; // case 1

	void unsetRelatingelement(EIfcrelconnectsstructuralactivity type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:RelatedStructuralActivity, base type: entity IfcStructuralActivity
	public boolean testRelatedstructuralactivity(EIfcrelconnectsstructuralactivity type) throws SdaiException;
	public EIfcstructuralactivity getRelatedstructuralactivity(EIfcrelconnectsstructuralactivity type) throws SdaiException;
	public void setRelatedstructuralactivity(EIfcrelconnectsstructuralactivity type, EIfcstructuralactivity value) throws SdaiException;
	public void unsetRelatedstructuralactivity(EIfcrelconnectsstructuralactivity type) throws SdaiException;

}
