/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing enumeration IfcEvaporativeCoolerTypeEnum

package jsdai.SIfc4;
import jsdai.lang.*;

public class EIfcevaporativecoolertypeenum {

	private static final int unset = 0;
	public static final int DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER = 1;	// DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER
	public static final int DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER = 2;	// DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER
	public static final int DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER = 3;	// DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER
	public static final int DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER = 4;	// DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER
	public static final int DIRECTEVAPORATIVEAIRWASHER = 5;	// DIRECTEVAPORATIVEAIRWASHER
	public static final int INDIRECTEVAPORATIVEPACKAGEAIRCOOLER = 6;	// INDIRECTEVAPORATIVEPACKAGEAIRCOOLER
	public static final int INDIRECTEVAPORATIVEWETCOIL = 7;	// INDIRECTEVAPORATIVEWETCOIL
	public static final int INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER = 8;	// INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER
	public static final int INDIRECTDIRECTCOMBINATION = 9;	// INDIRECTDIRECTCOMBINATION
	public static final int USERDEFINED = 10;	// USERDEFINED
	public static final int NOTDEFINED = 11;	// NOTDEFINED

	private static final int dim = 11;

	public static final String values[] = {"DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER", "DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER", "DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER", "DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER", "DIRECTEVAPORATIVEAIRWASHER", "INDIRECTEVAPORATIVEPACKAGEAIRCOOLER", "INDIRECTEVAPORATIVEWETCOIL", "INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER", "INDIRECTDIRECTCOMBINATION", "USERDEFINED", "NOTDEFINED"};

//-------- methods ---------

	private static boolean isSet(int value) { return ((value >= 1) && (value <= dim)); }

	public static int toInt(String str) {
		for (int i = 0; i < dim; i++) {
			if (values[i].equalsIgnoreCase(str)) return i+1;
		}
		return unset;
	}

	public static String toString(int value) {
		if (!isSet(value)) return "unset";
		return values[value-1];
	}
}
