/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcBuildingSystem

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcbuildingsystem extends EIfcsystem {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcbuildingsystem type) throws SdaiException;
	public int getPredefinedtype(EIfcbuildingsystem type) throws SdaiException;
	public void setPredefinedtype(EIfcbuildingsystem type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcbuildingsystem type) throws SdaiException;

}
