/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRelAssignsToGroupByFactor

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcrelassignstogroupbyfactor extends EIfcrelassignstogroup {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Factor, base type: REAL
	public boolean testFactor(EIfcrelassignstogroupbyfactor type) throws SdaiException;
	public double getFactor(EIfcrelassignstogroupbyfactor type) throws SdaiException;
	public void setFactor(EIfcrelassignstogroupbyfactor type, double value) throws SdaiException;
	public void unsetFactor(EIfcrelassignstogroupbyfactor type) throws SdaiException;

}
