/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing enumeration IfcPileTypeEnum

package jsdai.SIfc4;
import jsdai.lang.*;

public class EIfcpiletypeenum {

	private static final int unset = 0;
	public static final int BORED = 1;	// BORED
	public static final int DRIVEN = 2;	// DRIVEN
	public static final int JETGROUTING = 3;	// JETGROUTING
	public static final int COHESION = 4;	// COHESION
	public static final int FRICTION = 5;	// FRICTION
	public static final int SUPPORT = 6;	// SUPPORT
	public static final int USERDEFINED = 7;	// USERDEFINED
	public static final int NOTDEFINED = 8;	// NOTDEFINED

	private static final int dim = 8;

	public static final String values[] = {"BORED", "DRIVEN", "JETGROUTING", "COHESION", "FRICTION", "SUPPORT", "USERDEFINED", "NOTDEFINED"};

//-------- methods ---------

	private static boolean isSet(int value) { return ((value >= 1) && (value <= dim)); }

	public static int toInt(String str) {
		for (int i = 0; i < dim; i++) {
			if (values[i].equalsIgnoreCase(str)) return i+1;
		}
		return unset;
	}

	public static String toString(int value) {
		if (!isSet(value)) return "unset";
		return values[value-1];
	}
}
