/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRectangularPyramid

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcrectangularpyramid extends EIfccsgprimitive3d {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:XLength, base type: REAL
	public boolean testXlength(EIfcrectangularpyramid type) throws SdaiException;
	public double getXlength(EIfcrectangularpyramid type) throws SdaiException;
	public void setXlength(EIfcrectangularpyramid type, double value) throws SdaiException;
	public void unsetXlength(EIfcrectangularpyramid type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:YLength, base type: REAL
	public boolean testYlength(EIfcrectangularpyramid type) throws SdaiException;
	public double getYlength(EIfcrectangularpyramid type) throws SdaiException;
	public void setYlength(EIfcrectangularpyramid type, double value) throws SdaiException;
	public void unsetYlength(EIfcrectangularpyramid type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Height, base type: REAL
	public boolean testHeight(EIfcrectangularpyramid type) throws SdaiException;
	public double getHeight(EIfcrectangularpyramid type) throws SdaiException;
	public void setHeight(EIfcrectangularpyramid type, double value) throws SdaiException;
	public void unsetHeight(EIfcrectangularpyramid type) throws SdaiException;

}
