/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcShadingDeviceType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcshadingdevicetype extends EIfcbuildingelementtype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcshadingdevicetype type) throws SdaiException;
	public int getPredefinedtype(EIfcshadingdevicetype type) throws SdaiException;
	public void setPredefinedtype(EIfcshadingdevicetype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcshadingdevicetype type) throws SdaiException;

}
