/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcAirTerminal

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcairterminal extends EIfcflowterminal {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcairterminal type) throws SdaiException;
	public int getPredefinedtype(EIfcairterminal type) throws SdaiException;
	public void setPredefinedtype(EIfcairterminal type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcairterminal type) throws SdaiException;

}
