/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcStructuralConnectionCondition

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcstructuralconnectioncondition extends EEntity {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Name, base type: STRING
	public boolean testName(EIfcstructuralconnectioncondition type) throws SdaiException;
	public String getName(EIfcstructuralconnectioncondition type) throws SdaiException;
	public void setName(EIfcstructuralconnectioncondition type, String value) throws SdaiException;
	public void unsetName(EIfcstructuralconnectioncondition type) throws SdaiException;

}
