/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRelFillsElement

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcrelfillselement extends EIfcrelconnects {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:RelatingOpeningElement, base type: entity IfcOpeningElement
	public boolean testRelatingopeningelement(EIfcrelfillselement type) throws SdaiException;
	public EIfcopeningelement getRelatingopeningelement(EIfcrelfillselement type) throws SdaiException;
	public void setRelatingopeningelement(EIfcrelfillselement type, EIfcopeningelement value) throws SdaiException;
	public void unsetRelatingopeningelement(EIfcrelfillselement type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:RelatedBuildingElement, base type: entity IfcElement
	public boolean testRelatedbuildingelement(EIfcrelfillselement type) throws SdaiException;
	public EIfcelement getRelatedbuildingelement(EIfcrelfillselement type) throws SdaiException;
	public void setRelatedbuildingelement(EIfcrelfillselement type, EIfcelement value) throws SdaiException;
	public void unsetRelatedbuildingelement(EIfcrelfillselement type) throws SdaiException;

}
