/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcDiscreteAccessoryType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcdiscreteaccessorytype extends EIfcelementcomponenttype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcdiscreteaccessorytype type) throws SdaiException;
	public int getPredefinedtype(EIfcdiscreteaccessorytype type) throws SdaiException;
	public void setPredefinedtype(EIfcdiscreteaccessorytype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcdiscreteaccessorytype type) throws SdaiException;

}
