/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcTrimmedCurve

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfctrimmedcurve extends EIfcboundedcurve {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:BasisCurve, base type: entity IfcCurve
	public boolean testBasiscurve(EIfctrimmedcurve type) throws SdaiException;
	public EIfccurve getBasiscurve(EIfctrimmedcurve type) throws SdaiException;
	public void setBasiscurve(EIfctrimmedcurve type, EIfccurve value) throws SdaiException;
	public void unsetBasiscurve(EIfctrimmedcurve type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// methods for attribute: Trim1, base type: SET OF SELECT
	public boolean testTrim1(EIfctrimmedcurve type) throws SdaiException;
	public AIfctrimmingselect getTrim1(EIfctrimmedcurve type) throws SdaiException;
	public AIfctrimmingselect createTrim1(EIfctrimmedcurve type) throws SdaiException;
	public void unsetTrim1(EIfctrimmedcurve type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// methods for attribute: Trim2, base type: SET OF SELECT
	public boolean testTrim2(EIfctrimmedcurve type) throws SdaiException;
	public AIfctrimmingselect getTrim2(EIfctrimmedcurve type) throws SdaiException;
	public AIfctrimmingselect createTrim2(EIfctrimmedcurve type) throws SdaiException;
	public void unsetTrim2(EIfctrimmedcurve type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:SenseAgreement, base type: BOOLEAN
	public boolean testSenseagreement(EIfctrimmedcurve type) throws SdaiException;
	public boolean getSenseagreement(EIfctrimmedcurve type) throws SdaiException;
	public void setSenseagreement(EIfctrimmedcurve type, boolean value) throws SdaiException;
	public void unsetSenseagreement(EIfctrimmedcurve type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:MasterRepresentation, base type: ENUMERATION
	public boolean testMasterrepresentation(EIfctrimmedcurve type) throws SdaiException;
	public int getMasterrepresentation(EIfctrimmedcurve type) throws SdaiException;
	public void setMasterrepresentation(EIfctrimmedcurve type, int value) throws SdaiException;
	public void unsetMasterrepresentation(EIfctrimmedcurve type) throws SdaiException;

}
