/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRelAssociatesDocument

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcrelassociatesdocument extends EIfcrelassociates {

	// generateExplicitAttributeMethodDeclarations: 1
	// constants and methods for SELECT attribute: RelatingDocument
	boolean testRelatingdocument(EIfcrelassociatesdocument type) throws SdaiException;

	EEntity getRelatingdocument(EIfcrelassociatesdocument type) throws SdaiException; // case 1

	void setRelatingdocument(EIfcrelassociatesdocument type, EEntity value) throws SdaiException; // case 1

	void unsetRelatingdocument(EIfcrelassociatesdocument type) throws SdaiException;

}
