/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcLamp

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfclamp extends EIfcflowterminal {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfclamp type) throws SdaiException;
	public int getPredefinedtype(EIfclamp type) throws SdaiException;
	public void setPredefinedtype(EIfclamp type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfclamp type) throws SdaiException;

}
