/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing enumeration IfcPumpTypeEnum

package jsdai.SIfc4;
import jsdai.lang.*;

public class EIfcpumptypeenum {

	private static final int unset = 0;
	public static final int CIRCULATOR = 1;	// CIRCULATOR
	public static final int ENDSUCTION = 2;	// ENDSUCTION
	public static final int SPLITCASE = 3;	// SPLITCASE
	public static final int SUBMERSIBLEPUMP = 4;	// SUBMERSIBLEPUMP
	public static final int SUMPPUMP = 5;	// SUMPPUMP
	public static final int VERTICALINLINE = 6;	// VERTICALINLINE
	public static final int VERTICALTURBINE = 7;	// VERTICALTURBINE
	public static final int USERDEFINED = 8;	// USERDEFINED
	public static final int NOTDEFINED = 9;	// NOTDEFINED

	private static final int dim = 9;

	public static final String values[] = {"CIRCULATOR", "ENDSUCTION", "SPLITCASE", "SUBMERSIBLEPUMP", "SUMPPUMP", "VERTICALINLINE", "VERTICALTURBINE", "USERDEFINED", "NOTDEFINED"};

//-------- methods ---------

	private static boolean isSet(int value) { return ((value >= 1) && (value <= dim)); }

	public static int toInt(String str) {
		for (int i = 0; i < dim; i++) {
			if (values[i].equalsIgnoreCase(str)) return i+1;
		}
		return unset;
	}

	public static String toString(int value) {
		if (!isSet(value)) return "unset";
		return values[value-1];
	}
}
