/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcColumn

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfccolumn extends EIfcbuildingelement {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfccolumn type) throws SdaiException;
	public int getPredefinedtype(EIfccolumn type) throws SdaiException;
	public void setPredefinedtype(EIfccolumn type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfccolumn type) throws SdaiException;

}
