/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcSanitaryTerminalType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcsanitaryterminaltype extends EIfcflowterminaltype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcsanitaryterminaltype type) throws SdaiException;
	public int getPredefinedtype(EIfcsanitaryterminaltype type) throws SdaiException;
	public void setPredefinedtype(EIfcsanitaryterminaltype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcsanitaryterminaltype type) throws SdaiException;

}
