/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcOffsetCurve3D

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcoffsetcurve3d extends EIfccurve {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:BasisCurve, base type: entity IfcCurve
	public boolean testBasiscurve(EIfcoffsetcurve3d type) throws SdaiException;
	public EIfccurve getBasiscurve(EIfcoffsetcurve3d type) throws SdaiException;
	public void setBasiscurve(EIfcoffsetcurve3d type, EIfccurve value) throws SdaiException;
	public void unsetBasiscurve(EIfcoffsetcurve3d type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Distance, base type: REAL
	public boolean testDistance(EIfcoffsetcurve3d type) throws SdaiException;
	public double getDistance(EIfcoffsetcurve3d type) throws SdaiException;
	public void setDistance(EIfcoffsetcurve3d type, double value) throws SdaiException;
	public void unsetDistance(EIfcoffsetcurve3d type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:SelfIntersect, base type: LOGICAL
	public boolean testSelfintersect(EIfcoffsetcurve3d type) throws SdaiException;
	public int getSelfintersect(EIfcoffsetcurve3d type) throws SdaiException;
	public void setSelfintersect(EIfcoffsetcurve3d type, int value) throws SdaiException;
	public void unsetSelfintersect(EIfcoffsetcurve3d type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:RefDirection, base type: entity IfcDirection
	public boolean testRefdirection(EIfcoffsetcurve3d type) throws SdaiException;
	public EIfcdirection getRefdirection(EIfcoffsetcurve3d type) throws SdaiException;
	public void setRefdirection(EIfcoffsetcurve3d type, EIfcdirection value) throws SdaiException;
	public void unsetRefdirection(EIfcoffsetcurve3d type) throws SdaiException;

}
