/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcPropertyAbstraction

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcpropertyabstraction extends EEntity {

	// Inverse attribute - HasExternalReferences : SET[0:-2147483648] OF IfcExternalReferenceRelationship FOR RelatedResourceObjects
	public AIfcexternalreferencerelationship getHasexternalreferences(EIfcpropertyabstraction type, ASdaiModel domain) throws SdaiException;
}
