/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing enumeration IfcAudioVisualApplianceTypeEnum

package jsdai.SIfc4;
import jsdai.lang.*;

public class EIfcaudiovisualappliancetypeenum {

	private static final int unset = 0;
	public static final int AMPLIFIER = 1;	// AMPLIFIER
	public static final int CAMERA = 2;	// CAMERA
	public static final int DISPLAY = 3;	// DISPLAY
	public static final int MICROPHONE = 4;	// MICROPHONE
	public static final int PLAYER = 5;	// PLAYER
	public static final int PROJECTOR = 6;	// PROJECTOR
	public static final int RECEIVER = 7;	// RECEIVER
	public static final int SPEAKER = 8;	// SPEAKER
	public static final int SWITCHER = 9;	// SWITCHER
	public static final int TELEPHONE = 10;	// TELEPHONE
	public static final int TUNER = 11;	// TUNER
	public static final int USERDEFINED = 12;	// USERDEFINED
	public static final int NOTDEFINED = 13;	// NOTDEFINED

	private static final int dim = 13;

	public static final String values[] = {"AMPLIFIER", "CAMERA", "DISPLAY", "MICROPHONE", "PLAYER", "PROJECTOR", "RECEIVER", "SPEAKER", "SWITCHER", "TELEPHONE", "TUNER", "USERDEFINED", "NOTDEFINED"};

//-------- methods ---------

	private static boolean isSet(int value) { return ((value >= 1) && (value <= dim)); }

	public static int toInt(String str) {
		for (int i = 0; i < dim; i++) {
			if (values[i].equalsIgnoreCase(str)) return i+1;
		}
		return unset;
	}

	public static String toString(int value) {
		if (!isSet(value)) return "unset";
		return values[value-1];
	}
}
