/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcExtendedProperties

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcextendedproperties extends EIfcpropertyabstraction {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Name, base type: STRING
	public boolean testName(EIfcextendedproperties type) throws SdaiException;
	public String getName(EIfcextendedproperties type) throws SdaiException;
	public void setName(EIfcextendedproperties type, String value) throws SdaiException;
	public void unsetName(EIfcextendedproperties type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Description, base type: STRING
	public boolean testDescription(EIfcextendedproperties type) throws SdaiException;
	public String getDescription(EIfcextendedproperties type) throws SdaiException;
	public void setDescription(EIfcextendedproperties type, String value) throws SdaiException;
	public void unsetDescription(EIfcextendedproperties type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// methods for attribute: Properties, base type: SET OF ENTITY
	public boolean testProperties(EIfcextendedproperties type) throws SdaiException;
	public AIfcproperty getProperties(EIfcextendedproperties type) throws SdaiException;
	public AIfcproperty createProperties(EIfcextendedproperties type) throws SdaiException;
	public void unsetProperties(EIfcextendedproperties type) throws SdaiException;

}
