/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcRelAssignsToProcess

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcrelassignstoprocess extends EIfcrelassigns {

	// generateExplicitAttributeMethodDeclarations: 1
	// constants and methods for SELECT attribute: RelatingProcess
	boolean testRelatingprocess(EIfcrelassignstoprocess type) throws SdaiException;

	EEntity getRelatingprocess(EIfcrelassignstoprocess type) throws SdaiException; // case 1

	void setRelatingprocess(EIfcrelassignstoprocess type, EEntity value) throws SdaiException; // case 1

	void unsetRelatingprocess(EIfcrelassignstoprocess type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:QuantityInProcess, base type: entity IfcMeasureWithUnit
	public boolean testQuantityinprocess(EIfcrelassignstoprocess type) throws SdaiException;
	public EIfcmeasurewithunit getQuantityinprocess(EIfcrelassignstoprocess type) throws SdaiException;
	public void setQuantityinprocess(EIfcrelassignstoprocess type, EIfcmeasurewithunit value) throws SdaiException;
	public void unsetQuantityinprocess(EIfcrelassignstoprocess type) throws SdaiException;

}
