/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcShadingDevice

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcshadingdevice extends EIfcbuildingelement {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcshadingdevice type) throws SdaiException;
	public int getPredefinedtype(EIfcshadingdevice type) throws SdaiException;
	public void setPredefinedtype(EIfcshadingdevice type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcshadingdevice type) throws SdaiException;

}
