/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcStructuralLoadSingleDisplacementDistortion

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcstructuralloadsingledisplacementdistortion extends EIfcstructuralloadsingledisplacement {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Distortion, base type: REAL
	public boolean testDistortion(EIfcstructuralloadsingledisplacementdistortion type) throws SdaiException;
	public double getDistortion(EIfcstructuralloadsingledisplacementdistortion type) throws SdaiException;
	public void setDistortion(EIfcstructuralloadsingledisplacementdistortion type, double value) throws SdaiException;
	public void unsetDistortion(EIfcstructuralloadsingledisplacementdistortion type) throws SdaiException;

}
