/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcPerformanceHistory

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcperformancehistory extends EIfccontrol {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:LifeCyclePhase, base type: STRING
	public boolean testLifecyclephase(EIfcperformancehistory type) throws SdaiException;
	public String getLifecyclephase(EIfcperformancehistory type) throws SdaiException;
	public void setLifecyclephase(EIfcperformancehistory type, String value) throws SdaiException;
	public void unsetLifecyclephase(EIfcperformancehistory type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcperformancehistory type) throws SdaiException;
	public int getPredefinedtype(EIfcperformancehistory type) throws SdaiException;
	public void setPredefinedtype(EIfcperformancehistory type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcperformancehistory type) throws SdaiException;

}
