/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing enumeration IfcReinforcingBarTypeEnum

package jsdai.SIfc4;
import jsdai.lang.*;

public class EIfcreinforcingbartypeenum {

	private static final int unset = 0;
	public static final int ANCHORING = 1;	// ANCHORING
	public static final int EDGE = 2;	// EDGE
	public static final int LIGATURE = 3;	// LIGATURE
	public static final int MAIN = 4;	// MAIN
	public static final int PUNCHING = 5;	// PUNCHING
	public static final int RING = 6;	// RING
	public static final int SHEAR = 7;	// SHEAR
	public static final int STUD = 8;	// STUD
	public static final int USERDEFINED = 9;	// USERDEFINED
	public static final int NOTDEFINED = 10;	// NOTDEFINED

	private static final int dim = 10;

	public static final String values[] = {"ANCHORING", "EDGE", "LIGATURE", "MAIN", "PUNCHING", "RING", "SHEAR", "STUD", "USERDEFINED", "NOTDEFINED"};

//-------- methods ---------

	private static boolean isSet(int value) { return ((value >= 1) && (value <= dim)); }

	public static int toInt(String str) {
		for (int i = 0; i < dim; i++) {
			if (values[i].equalsIgnoreCase(str)) return i+1;
		}
		return unset;
	}

	public static String toString(int value) {
		if (!isSet(value)) return "unset";
		return values[value-1];
	}
}
