/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcConstructionProductResource

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcconstructionproductresource extends EIfcconstructionresource {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcconstructionproductresource type) throws SdaiException;
	public int getPredefinedtype(EIfcconstructionproductresource type) throws SdaiException;
	public void setPredefinedtype(EIfcconstructionproductresource type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcconstructionproductresource type) throws SdaiException;

}
