/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcStructuralLoadSingleForceWarping

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcstructuralloadsingleforcewarping extends EIfcstructuralloadsingleforce {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:WarpingMoment, base type: REAL
	public boolean testWarpingmoment(EIfcstructuralloadsingleforcewarping type) throws SdaiException;
	public double getWarpingmoment(EIfcstructuralloadsingleforcewarping type) throws SdaiException;
	public void setWarpingmoment(EIfcstructuralloadsingleforcewarping type, double value) throws SdaiException;
	public void unsetWarpingmoment(EIfcstructuralloadsingleforcewarping type) throws SdaiException;

}
