/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcBuildingElement

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcbuildingelement extends EIfcelement {

	// Inverse attribute - HasCoverings : SET[0:-2147483648] OF IfcRelCoversBldgElements FOR RelatingBuildingElement
	public AIfcrelcoversbldgelements getHascoverings(EIfcbuildingelement type, ASdaiModel domain) throws SdaiException;
}
