/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcPropertyDependencyRelationship

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcpropertydependencyrelationship extends EIfcresourcelevelrelationship {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:DependingProperty, base type: entity IfcProperty
	public boolean testDependingproperty(EIfcpropertydependencyrelationship type) throws SdaiException;
	public EIfcproperty getDependingproperty(EIfcpropertydependencyrelationship type) throws SdaiException;
	public void setDependingproperty(EIfcpropertydependencyrelationship type, EIfcproperty value) throws SdaiException;
	public void unsetDependingproperty(EIfcpropertydependencyrelationship type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:DependantProperty, base type: entity IfcProperty
	public boolean testDependantproperty(EIfcpropertydependencyrelationship type) throws SdaiException;
	public EIfcproperty getDependantproperty(EIfcpropertydependencyrelationship type) throws SdaiException;
	public void setDependantproperty(EIfcpropertydependencyrelationship type, EIfcproperty value) throws SdaiException;
	public void unsetDependantproperty(EIfcpropertydependencyrelationship type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:Expression, base type: STRING
	public boolean testExpression(EIfcpropertydependencyrelationship type) throws SdaiException;
	public String getExpression(EIfcpropertydependencyrelationship type) throws SdaiException;
	public void setExpression(EIfcpropertydependencyrelationship type, String value) throws SdaiException;
	public void unsetExpression(EIfcpropertydependencyrelationship type) throws SdaiException;

}
