/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java class implementing enumeration IfcBeamTypeEnum

package jsdai.SIfc4;
import jsdai.lang.*;

public class EIfcbeamtypeenum {

	private static final int unset = 0;
	public static final int BEAM = 1;	// BEAM
	public static final int JOIST = 2;	// JOIST
	public static final int HOLLOWCORE = 3;	// HOLLOWCORE
	public static final int LINTEL = 4;	// LINTEL
	public static final int SPANDREL = 5;	// SPANDREL
	public static final int T_BEAM = 6;	// T_BEAM
	public static final int USERDEFINED = 7;	// USERDEFINED
	public static final int NOTDEFINED = 8;	// NOTDEFINED

	private static final int dim = 8;

	public static final String values[] = {"BEAM", "JOIST", "HOLLOWCORE", "LINTEL", "SPANDREL", "T_BEAM", "USERDEFINED", "NOTDEFINED"};

//-------- methods ---------

	private static boolean isSet(int value) { return ((value >= 1) && (value <= dim)); }

	public static int toInt(String str) {
		for (int i = 0; i < dim; i++) {
			if (values[i].equalsIgnoreCase(str)) return i+1;
		}
		return unset;
	}

	public static String toString(int value) {
		if (!isSet(value)) return "unset";
		return values[value-1];
	}
}
