/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcDoorPanelProperties

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcdoorpanelproperties extends EIfcpredefinedpropertyset {

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:PanelDepth, base type: REAL
	public boolean testPaneldepth(EIfcdoorpanelproperties type) throws SdaiException;
	public double getPaneldepth(EIfcdoorpanelproperties type) throws SdaiException;
	public void setPaneldepth(EIfcdoorpanelproperties type, double value) throws SdaiException;
	public void unsetPaneldepth(EIfcdoorpanelproperties type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PanelOperation, base type: ENUMERATION
	public boolean testPaneloperation(EIfcdoorpanelproperties type) throws SdaiException;
	public int getPaneloperation(EIfcdoorpanelproperties type) throws SdaiException;
	public void setPaneloperation(EIfcdoorpanelproperties type, int value) throws SdaiException;
	public void unsetPaneloperation(EIfcdoorpanelproperties type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	/// methods for attribute:PanelWidth, base type: REAL
	public boolean testPanelwidth(EIfcdoorpanelproperties type) throws SdaiException;
	public double getPanelwidth(EIfcdoorpanelproperties type) throws SdaiException;
	public void setPanelwidth(EIfcdoorpanelproperties type, double value) throws SdaiException;
	public void unsetPanelwidth(EIfcdoorpanelproperties type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PanelPosition, base type: ENUMERATION
	public boolean testPanelposition(EIfcdoorpanelproperties type) throws SdaiException;
	public int getPanelposition(EIfcdoorpanelproperties type) throws SdaiException;
	public void setPanelposition(EIfcdoorpanelproperties type, int value) throws SdaiException;
	public void unsetPanelposition(EIfcdoorpanelproperties type) throws SdaiException;

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:ShapeAspectStyle, base type: entity IfcShapeAspect
	public boolean testShapeaspectstyle(EIfcdoorpanelproperties type) throws SdaiException;
	public EIfcshapeaspect getShapeaspectstyle(EIfcdoorpanelproperties type) throws SdaiException;
	public void setShapeaspectstyle(EIfcdoorpanelproperties type, EIfcshapeaspect value) throws SdaiException;
	public void unsetShapeaspectstyle(EIfcdoorpanelproperties type) throws SdaiException;

}
