/* Generated by JSDAI Express Compiler, version 4.3.2, build 500, 2011-12-13 */

// Java interface for entity IfcDuctSegmentType

package jsdai.SIfc4;
import jsdai.lang.*;

public interface EIfcductsegmenttype extends EIfcflowsegmenttype {

	// generateExplicitAttributeMethodDeclarations: 1
	// attribute:PredefinedType, base type: ENUMERATION
	public boolean testPredefinedtype(EIfcductsegmenttype type) throws SdaiException;
	public int getPredefinedtype(EIfcductsegmenttype type) throws SdaiException;
	public void setPredefinedtype(EIfcductsegmenttype type, int value) throws SdaiException;
	public void unsetPredefinedtype(EIfcductsegmenttype type) throws SdaiException;

}
